environment: release
serverKey: helloworld
clientKey: hellokitty
enableDebug: false
db:
  game:
    user: root
    password: password
    address: "localhost:3306"
    name: game
    maxIdleConns: 10
    maxOpenConns: 20
  manage:
    user: root
    password: password
    address: "localhost:3306"
    name: manage
    maxIdleConns: 10
    maxOpenConns: 20
  serverList:
    - mame: router
      address: "localhost:9010"
tableFiles: testdata/tables
scriptFiles: testdata/scripts
