version: '3'
services:
  router_server:
    restart: always
    # image: registry.cn-hangzhou.aliyuncs.com/guogeer/gofishing-game:v2.0.1
    image: registry.cn-hangzhou.aliyuncs.com/guogeer/gofishing-game:v2.0.4
    container_name: "router_server"
    command: ./router_server
    ports:
      - "9010:9010"
    networks:
      - gamenet
  gateway_server:
    image: registry.cn-hangzhou.aliyuncs.com/guogeer/gofishing-game:v2.0.4
    restart: always
    container_name: "gateway_server"
    # 配置gateway对外地址
    command: ./gateway_server --port 8020 --proxy localhost
    ports:
      - "8020:8020"
    networks:
      - gamenet
  cache_server:
    image: registry.cn-hangzhou.aliyuncs.com/guogeer/gofishing-game:v2.0.4
    restart: always
    container_name: "cache_server"
    command: ./cache_server --port 9000
    ports:
      - "9000:9000"
    networks:
      - gamenet
  hall_server:
    image: registry.cn-hangzhou.aliyuncs.com/guogeer/gofishing-game:v2.0.4
    restart: always
    container_name: "hall_server"
    command: ./hall_server --port 19001
    networks:
      - gamenet
  games_server:
    image: registry.cn-hangzhou.aliyuncs.com/guogeer/gofishing-game:v2.0.4
    restart: always
    container_name: "games_server"
    command: ./games_server --port 19002
    networks:
      - gamenet
  login_server:
    image: registry.cn-hangzhou.aliyuncs.com/guogeer/gofishing-game:v2.0.4
    restart: always
    container_name: "login_server"
    command: ./login_server --rootpath demo
    ports:
      - "9501:9501"
    networks:
      - gamenet
  mariadb:
    image: hub.atomgit.com/amd64/mariadb:10.6
    container_name: "mariadb"
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    volumes:
      - /etc/localtime:/etc/localtime
      - /tmp/dockerdata/mariadb:/var/lib/mysql    
    ports:
      - "3306:3306"
    networks:
      - gamenet
networks:
  gamenet:
    driver: bridge