// 大厅

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.25.1
// source: internal/pb/common.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CD struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ExpireMs int64 `protobuf:"varint,1,opt,name=ExpireMs,proto3" json:"ExpireMs,omitempty"` // 过期时间，单位ms
	PeriodMs int64 `protobuf:"varint,2,opt,name=PeriodMs,proto3" json:"PeriodMs,omitempty"` // 周期单位ms
}

func (x *CD) Reset() {
	*x = CD{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_pb_common_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CD) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CD) ProtoMessage() {}

func (x *CD) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_common_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CD.ProtoReflect.Descriptor instead.
func (*CD) Descriptor() ([]byte, []int) {
	return file_internal_pb_common_proto_rawDescGZIP(), []int{0}
}

func (x *CD) GetExpireMs() int64 {
	if x != nil {
		return x.ExpireMs
	}
	return 0
}

func (x *CD) GetPeriodMs() int64 {
	if x != nil {
		return x.PeriodMs
	}
	return 0
}

type SimpleUserInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UId        int32  `protobuf:"varint,1,opt,name=UId,proto3" json:"UId,omitempty"`
	Nickname   string `protobuf:"bytes,2,opt,name=Nickname,proto3" json:"Nickname,omitempty"`
	Icon       string `protobuf:"bytes,3,opt,name=Icon,proto3" json:"Icon,omitempty"`
	VIP        int32  `protobuf:"varint,4,opt,name=VIP,proto3" json:"VIP,omitempty"`
	Sex        int32  `protobuf:"varint,5,opt,name=Sex,proto3" json:"Sex,omitempty"`
	Level      int32  `protobuf:"varint,6,opt,name=Level,proto3" json:"Level,omitempty"`
	BuildLevel int32  `protobuf:"varint,7,opt,name=BuildLevel,proto3" json:"BuildLevel,omitempty"`
}

func (x *SimpleUserInfo) Reset() {
	*x = SimpleUserInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_pb_common_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SimpleUserInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SimpleUserInfo) ProtoMessage() {}

func (x *SimpleUserInfo) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_common_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SimpleUserInfo.ProtoReflect.Descriptor instead.
func (*SimpleUserInfo) Descriptor() ([]byte, []int) {
	return file_internal_pb_common_proto_rawDescGZIP(), []int{1}
}

func (x *SimpleUserInfo) GetUId() int32 {
	if x != nil {
		return x.UId
	}
	return 0
}

func (x *SimpleUserInfo) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *SimpleUserInfo) GetIcon() string {
	if x != nil {
		return x.Icon
	}
	return ""
}

func (x *SimpleUserInfo) GetVIP() int32 {
	if x != nil {
		return x.VIP
	}
	return 0
}

func (x *SimpleUserInfo) GetSex() int32 {
	if x != nil {
		return x.Sex
	}
	return 0
}

func (x *SimpleUserInfo) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *SimpleUserInfo) GetBuildLevel() int32 {
	if x != nil {
		return x.BuildLevel
	}
	return 0
}

type Item struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       int32 `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Num      int64 `protobuf:"varint,2,opt,name=Num,proto3" json:"Num,omitempty"`
	Balance  int64 `protobuf:"varint,3,opt,name=Balance,proto3" json:"Balance,omitempty"`
	ExpireTs int64 `protobuf:"varint,4,opt,name=ExpireTs,proto3" json:"ExpireTs,omitempty"`
	UpdateTs int32 `protobuf:"varint,5,opt,name=UpdateTs,proto3" json:"UpdateTs,omitempty"`
}

func (x *Item) Reset() {
	*x = Item{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_pb_common_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Item) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Item) ProtoMessage() {}

func (x *Item) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_common_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Item.ProtoReflect.Descriptor instead.
func (*Item) Descriptor() ([]byte, []int) {
	return file_internal_pb_common_proto_rawDescGZIP(), []int{2}
}

func (x *Item) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Item) GetNum() int64 {
	if x != nil {
		return x.Num
	}
	return 0
}

func (x *Item) GetBalance() int64 {
	if x != nil {
		return x.Balance
	}
	return 0
}

func (x *Item) GetExpireTs() int64 {
	if x != nil {
		return x.ExpireTs
	}
	return 0
}

func (x *Item) GetUpdateTs() int32 {
	if x != nil {
		return x.UpdateTs
	}
	return 0
}

type Bundle struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Version    string `protobuf:"bytes,1,opt,name=Version,proto3" json:"Version,omitempty"`
	BundleName string `protobuf:"bytes,2,opt,name=BundleName,proto3" json:"BundleName,omitempty"`
	Url        string `protobuf:"bytes,3,opt,name=Url,proto3" json:"Url,omitempty"`
}

func (x *Bundle) Reset() {
	*x = Bundle{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_pb_common_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Bundle) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Bundle) ProtoMessage() {}

func (x *Bundle) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_common_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Bundle.ProtoReflect.Descriptor instead.
func (*Bundle) Descriptor() ([]byte, []int) {
	return file_internal_pb_common_proto_rawDescGZIP(), []int{3}
}

func (x *Bundle) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *Bundle) GetBundleName() string {
	if x != nil {
		return x.BundleName
	}
	return ""
}

func (x *Bundle) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type LastVersion struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	WaitUpdateVersion []*WaitUpdateVersion `protobuf:"bytes,1,rep,name=WaitUpdateVersion,proto3" json:"WaitUpdateVersion,omitempty"`
}

func (x *LastVersion) Reset() {
	*x = LastVersion{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_pb_common_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LastVersion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LastVersion) ProtoMessage() {}

func (x *LastVersion) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_common_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LastVersion.ProtoReflect.Descriptor instead.
func (*LastVersion) Descriptor() ([]byte, []int) {
	return file_internal_pb_common_proto_rawDescGZIP(), []int{4}
}

func (x *LastVersion) GetWaitUpdateVersion() []*WaitUpdateVersion {
	if x != nil {
		return x.WaitUpdateVersion
	}
	return nil
}

type WaitUpdateVersion struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type      string    `protobuf:"bytes,1,opt,name=Type,proto3" json:"Type,omitempty"`
	HotUpdate int32     `protobuf:"varint,2,opt,name=HotUpdate,proto3" json:"HotUpdate,omitempty"`
	Reward    string    `protobuf:"bytes,3,opt,name=Reward,proto3" json:"Reward,omitempty"`
	Version   string    `protobuf:"bytes,4,opt,name=Version,proto3" json:"Version,omitempty"`
	ChanId    string    `protobuf:"bytes,5,opt,name=ChanId,proto3" json:"ChanId,omitempty"`
	ChangeLog string    `protobuf:"bytes,6,opt,name=ChangeLog,proto3" json:"ChangeLog,omitempty"`
	Url       string    `protobuf:"bytes,7,opt,name=Url,proto3" json:"Url,omitempty"`
	Config    string    `protobuf:"bytes,8,opt,name=Config,proto3" json:"Config,omitempty"`
	Whitelist string    `protobuf:"bytes,9,opt,name=Whitelist,proto3" json:"Whitelist,omitempty"`
	JsonValue string    `protobuf:"bytes,10,opt,name=JsonValue,proto3" json:"JsonValue,omitempty"`
	AllowIps  string    `protobuf:"bytes,11,opt,name=AllowIps,proto3" json:"AllowIps,omitempty"`
	TablesUrl string    `protobuf:"bytes,12,opt,name=TablesUrl,proto3" json:"TablesUrl,omitempty"`
	Bundles   []*Bundle `protobuf:"bytes,13,rep,name=Bundles,proto3" json:"Bundles,omitempty"`
}

func (x *WaitUpdateVersion) Reset() {
	*x = WaitUpdateVersion{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_pb_common_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WaitUpdateVersion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WaitUpdateVersion) ProtoMessage() {}

func (x *WaitUpdateVersion) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_common_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WaitUpdateVersion.ProtoReflect.Descriptor instead.
func (*WaitUpdateVersion) Descriptor() ([]byte, []int) {
	return file_internal_pb_common_proto_rawDescGZIP(), []int{5}
}

func (x *WaitUpdateVersion) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *WaitUpdateVersion) GetHotUpdate() int32 {
	if x != nil {
		return x.HotUpdate
	}
	return 0
}

func (x *WaitUpdateVersion) GetReward() string {
	if x != nil {
		return x.Reward
	}
	return ""
}

func (x *WaitUpdateVersion) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *WaitUpdateVersion) GetChanId() string {
	if x != nil {
		return x.ChanId
	}
	return ""
}

func (x *WaitUpdateVersion) GetChangeLog() string {
	if x != nil {
		return x.ChangeLog
	}
	return ""
}

func (x *WaitUpdateVersion) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *WaitUpdateVersion) GetConfig() string {
	if x != nil {
		return x.Config
	}
	return ""
}

func (x *WaitUpdateVersion) GetWhitelist() string {
	if x != nil {
		return x.Whitelist
	}
	return ""
}

func (x *WaitUpdateVersion) GetJsonValue() string {
	if x != nil {
		return x.JsonValue
	}
	return ""
}

func (x *WaitUpdateVersion) GetAllowIps() string {
	if x != nil {
		return x.AllowIps
	}
	return ""
}

func (x *WaitUpdateVersion) GetTablesUrl() string {
	if x != nil {
		return x.TablesUrl
	}
	return ""
}

func (x *WaitUpdateVersion) GetBundles() []*Bundle {
	if x != nil {
		return x.Bundles
	}
	return nil
}

type Task struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id     int32 `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Num    int64 `protobuf:"varint,2,opt,name=Num,proto3" json:"Num,omitempty"`     // 当前进度
	Total  int64 `protobuf:"varint,3,opt,name=Total,proto3" json:"Total,omitempty"` // 总进度
	Status int32 `protobuf:"varint,4,opt,name=Status,proto3" json:"Status,omitempty"`
}

func (x *Task) Reset() {
	*x = Task{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_pb_common_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Task) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Task) ProtoMessage() {}

func (x *Task) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_common_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Task.ProtoReflect.Descriptor instead.
func (*Task) Descriptor() ([]byte, []int) {
	return file_internal_pb_common_proto_rawDescGZIP(), []int{6}
}

func (x *Task) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Task) GetNum() int64 {
	if x != nil {
		return x.Num
	}
	return 0
}

func (x *Task) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *Task) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

var File_internal_pb_common_proto protoreflect.FileDescriptor

var file_internal_pb_common_proto_rawDesc = []byte{
	0x0a, 0x18, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x70, 0x62, 0x2f, 0x63, 0x6f,
	0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70, 0x62, 0x22, 0x3c,
	0x0a, 0x02, 0x43, 0x44, 0x12, 0x1a, 0x0a, 0x08, 0x45, 0x78, 0x70, 0x69, 0x72, 0x65, 0x4d, 0x73,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x45, 0x78, 0x70, 0x69, 0x72, 0x65, 0x4d, 0x73,
	0x12, 0x1a, 0x0a, 0x08, 0x50, 0x65, 0x72, 0x69, 0x6f, 0x64, 0x4d, 0x73, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x08, 0x50, 0x65, 0x72, 0x69, 0x6f, 0x64, 0x4d, 0x73, 0x22, 0xac, 0x01, 0x0a,
	0x0e, 0x53, 0x69, 0x6d, 0x70, 0x6c, 0x65, 0x55, 0x73, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x12,
	0x10, 0x0a, 0x03, 0x55, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x55, 0x49,
	0x64, 0x12, 0x1a, 0x0a, 0x08, 0x4e, 0x69, 0x63, 0x6b, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x4e, 0x69, 0x63, 0x6b, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a,
	0x04, 0x49, 0x63, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x49, 0x63, 0x6f,
	0x6e, 0x12, 0x10, 0x0a, 0x03, 0x56, 0x49, 0x50, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03,
	0x56, 0x49, 0x50, 0x12, 0x10, 0x0a, 0x03, 0x53, 0x65, 0x78, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x03, 0x53, 0x65, 0x78, 0x12, 0x14, 0x0a, 0x05, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x18, 0x06,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x12, 0x1e, 0x0a, 0x0a, 0x42,
	0x75, 0x69, 0x6c, 0x64, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x18, 0x07, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x0a, 0x42, 0x75, 0x69, 0x6c, 0x64, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x22, 0x7a, 0x0a, 0x04, 0x49,
	0x74, 0x65, 0x6d, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x02, 0x49, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x4e, 0x75, 0x6d, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x03, 0x4e, 0x75, 0x6d, 0x12, 0x18, 0x0a, 0x07, 0x42, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x42, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x12,
	0x1a, 0x0a, 0x08, 0x45, 0x78, 0x70, 0x69, 0x72, 0x65, 0x54, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x08, 0x45, 0x78, 0x70, 0x69, 0x72, 0x65, 0x54, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x55,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x54, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x55,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x54, 0x73, 0x22, 0x54, 0x0a, 0x06, 0x42, 0x75, 0x6e, 0x64, 0x6c,
	0x65, 0x12, 0x18, 0x0a, 0x07, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x1e, 0x0a, 0x0a, 0x42,
	0x75, 0x6e, 0x64, 0x6c, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0a, 0x42, 0x75, 0x6e, 0x64, 0x6c, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x55,
	0x72, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x55, 0x72, 0x6c, 0x22, 0x52, 0x0a,
	0x0b, 0x4c, 0x61, 0x73, 0x74, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x43, 0x0a, 0x11,
	0x57, 0x61, 0x69, 0x74, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f,
	0x6e, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x70, 0x62, 0x2e, 0x57, 0x61, 0x69,
	0x74, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x11,
	0x57, 0x61, 0x69, 0x74, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f,
	0x6e, 0x22, 0xf3, 0x02, 0x0a, 0x11, 0x57, 0x61, 0x69, 0x74, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x54, 0x79, 0x70, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x48,
	0x6f, 0x74, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09,
	0x48, 0x6f, 0x74, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x52, 0x65, 0x77,
	0x61, 0x72, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x52, 0x65, 0x77, 0x61, 0x72,
	0x64, 0x12, 0x18, 0x0a, 0x07, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x16, 0x0a, 0x06, 0x43,
	0x68, 0x61, 0x6e, 0x49, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x43, 0x68, 0x61,
	0x6e, 0x49, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x4c, 0x6f, 0x67,
	0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x4c, 0x6f,
	0x67, 0x12, 0x10, 0x0a, 0x03, 0x55, 0x72, 0x6c, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03,
	0x55, 0x72, 0x6c, 0x12, 0x16, 0x0a, 0x06, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x18, 0x08, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12, 0x1c, 0x0a, 0x09, 0x57,
	0x68, 0x69, 0x74, 0x65, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09,
	0x57, 0x68, 0x69, 0x74, 0x65, 0x6c, 0x69, 0x73, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x4a, 0x73, 0x6f,
	0x6e, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x4a, 0x73,
	0x6f, 0x6e, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x41, 0x6c, 0x6c, 0x6f, 0x77,
	0x49, 0x70, 0x73, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x41, 0x6c, 0x6c, 0x6f, 0x77,
	0x49, 0x70, 0x73, 0x12, 0x1c, 0x0a, 0x09, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x73, 0x55, 0x72, 0x6c,
	0x18, 0x0c, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x73, 0x55, 0x72,
	0x6c, 0x12, 0x24, 0x0a, 0x07, 0x42, 0x75, 0x6e, 0x64, 0x6c, 0x65, 0x73, 0x18, 0x0d, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x70, 0x62, 0x2e, 0x42, 0x75, 0x6e, 0x64, 0x6c, 0x65, 0x52, 0x07,
	0x42, 0x75, 0x6e, 0x64, 0x6c, 0x65, 0x73, 0x22, 0x56, 0x0a, 0x04, 0x54, 0x61, 0x73, 0x6b, 0x12,
	0x0e, 0x0a, 0x02, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x49, 0x64, 0x12,
	0x10, 0x0a, 0x03, 0x4e, 0x75, 0x6d, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x4e, 0x75,
	0x6d, 0x12, 0x14, 0x0a, 0x05, 0x54, 0x6f, 0x74, 0x61, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x05, 0x54, 0x6f, 0x74, 0x61, 0x6c, 0x12, 0x16, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x42,
	0x06, 0x5a, 0x04, 0x2e, 0x3b, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_internal_pb_common_proto_rawDescOnce sync.Once
	file_internal_pb_common_proto_rawDescData = file_internal_pb_common_proto_rawDesc
)

func file_internal_pb_common_proto_rawDescGZIP() []byte {
	file_internal_pb_common_proto_rawDescOnce.Do(func() {
		file_internal_pb_common_proto_rawDescData = protoimpl.X.CompressGZIP(file_internal_pb_common_proto_rawDescData)
	})
	return file_internal_pb_common_proto_rawDescData
}

var file_internal_pb_common_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_internal_pb_common_proto_goTypes = []interface{}{
	(*CD)(nil),                // 0: pb.CD
	(*SimpleUserInfo)(nil),    // 1: pb.SimpleUserInfo
	(*Item)(nil),              // 2: pb.Item
	(*Bundle)(nil),            // 3: pb.Bundle
	(*LastVersion)(nil),       // 4: pb.LastVersion
	(*WaitUpdateVersion)(nil), // 5: pb.WaitUpdateVersion
	(*Task)(nil),              // 6: pb.Task
}
var file_internal_pb_common_proto_depIdxs = []int32{
	5, // 0: pb.LastVersion.WaitUpdateVersion:type_name -> pb.WaitUpdateVersion
	3, // 1: pb.WaitUpdateVersion.Bundles:type_name -> pb.Bundle
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_internal_pb_common_proto_init() }
func file_internal_pb_common_proto_init() {
	if File_internal_pb_common_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_internal_pb_common_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CD); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_pb_common_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SimpleUserInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_pb_common_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Item); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_pb_common_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Bundle); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_pb_common_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LastVersion); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_pb_common_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WaitUpdateVersion); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_pb_common_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Task); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_internal_pb_common_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_pb_common_proto_goTypes,
		DependencyIndexes: file_internal_pb_common_proto_depIdxs,
		MessageInfos:      file_internal_pb_common_proto_msgTypes,
	}.Build()
	File_internal_pb_common_proto = out.File
	file_internal_pb_common_proto_rawDesc = nil
	file_internal_pb_common_proto_goTypes = nil
	file_internal_pb_common_proto_depIdxs = nil
}
