// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.25.1
// source: internal/pb/global.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UserInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UId           int32  `protobuf:"varint,1,opt,name=UId,proto3" json:"UId,omitempty"`
	Name          string `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	Address       string `protobuf:"bytes,3,opt,name=Address,proto3" json:"Address,omitempty"`
	Account       string `protobuf:"bytes,4,opt,name=Account,proto3" json:"Account,omitempty"`
	Password      string `protobuf:"bytes,5,opt,name=Password,proto3" json:"Password,omitempty"`
	Plate         string `protobuf:"bytes,6,opt,name=Plate,proto3" json:"Plate,omitempty"`
	OpenId        string `protobuf:"bytes,7,opt,name=OpenId,proto3" json:"OpenId,omitempty"`
	ChanId        string `protobuf:"bytes,9,opt,name=ChanId,proto3" json:"ChanId,omitempty"`
	Nickname      string `protobuf:"bytes,10,opt,name=Nickname,proto3" json:"Nickname,omitempty"`
	Sex           int32  `protobuf:"varint,11,opt,name=Sex,proto3" json:"Sex,omitempty"`
	VIP           int32  `protobuf:"varint,12,opt,name=VIP,proto3" json:"VIP,omitempty"`
	Icon          string `protobuf:"bytes,13,opt,name=Icon,proto3" json:"Icon,omitempty"`
	Imsi          string `protobuf:"bytes,14,opt,name=Imsi,proto3" json:"Imsi,omitempty"`
	Imei          string `protobuf:"bytes,15,opt,name=Imei,proto3" json:"Imei,omitempty"`
	Mac           string `protobuf:"bytes,16,opt,name=Mac,proto3" json:"Mac,omitempty"`
	Phone         string `protobuf:"bytes,17,opt,name=Phone,proto3" json:"Phone,omitempty"`
	OS            string `protobuf:"bytes,18,opt,name=OS,proto3" json:"OS,omitempty"`
	NetMode       string `protobuf:"bytes,19,opt,name=NetMode,proto3" json:"NetMode,omitempty"`
	Version       string `protobuf:"bytes,20,opt,name=Version,proto3" json:"Version,omitempty"`
	PhoneBrand    string `protobuf:"bytes,21,opt,name=PhoneBrand,proto3" json:"PhoneBrand,omitempty"`
	NewPassword   string `protobuf:"bytes,22,opt,name=NewPassword,proto3" json:"NewPassword,omitempty"`
	Method        string `protobuf:"bytes,23,opt,name=Method,proto3" json:"Method,omitempty"`
	IDFA          string `protobuf:"bytes,24,opt,name=IDFA,proto3" json:"IDFA,omitempty"` // IOS设备标识
	SubId         int32  `protobuf:"varint,25,opt,name=SubId,proto3" json:"SubId,omitempty"`
	IP            string `protobuf:"bytes,26,opt,name=IP,proto3" json:"IP,omitempty"`
	IPLimit       int32  `protobuf:"varint,27,opt,name=IPLimit,proto3" json:"IPLimit,omitempty"`
	IPLimitPerDay int32  `protobuf:"varint,28,opt,name=IPLimitPerDay,proto3" json:"IPLimitPerDay,omitempty"`
	Token         string `protobuf:"bytes,30,opt,name=Token,proto3" json:"Token,omitempty"`
	Level         int32  `protobuf:"varint,31,opt,name=Level,proto3" json:"Level,omitempty"`
	CreateTime    string `protobuf:"bytes,34,opt,name=CreateTime,proto3" json:"CreateTime,omitempty"`
	ServerName    string `protobuf:"bytes,35,opt,name=ServerName,proto3" json:"ServerName,omitempty"`
	Email         string `protobuf:"bytes,36,opt,name=Email,proto3" json:"Email,omitempty"`
	PlateIcon     string `protobuf:"bytes,37,opt,name=PlateIcon,proto3" json:"PlateIcon,omitempty"`
}

func (x *UserInfo) Reset() {
	*x = UserInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_pb_global_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserInfo) ProtoMessage() {}

func (x *UserInfo) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_global_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserInfo.ProtoReflect.Descriptor instead.
func (*UserInfo) Descriptor() ([]byte, []int) {
	return file_internal_pb_global_proto_rawDescGZIP(), []int{0}
}

func (x *UserInfo) GetUId() int32 {
	if x != nil {
		return x.UId
	}
	return 0
}

func (x *UserInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UserInfo) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *UserInfo) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

func (x *UserInfo) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *UserInfo) GetPlate() string {
	if x != nil {
		return x.Plate
	}
	return ""
}

func (x *UserInfo) GetOpenId() string {
	if x != nil {
		return x.OpenId
	}
	return ""
}

func (x *UserInfo) GetChanId() string {
	if x != nil {
		return x.ChanId
	}
	return ""
}

func (x *UserInfo) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *UserInfo) GetSex() int32 {
	if x != nil {
		return x.Sex
	}
	return 0
}

func (x *UserInfo) GetVIP() int32 {
	if x != nil {
		return x.VIP
	}
	return 0
}

func (x *UserInfo) GetIcon() string {
	if x != nil {
		return x.Icon
	}
	return ""
}

func (x *UserInfo) GetImsi() string {
	if x != nil {
		return x.Imsi
	}
	return ""
}

func (x *UserInfo) GetImei() string {
	if x != nil {
		return x.Imei
	}
	return ""
}

func (x *UserInfo) GetMac() string {
	if x != nil {
		return x.Mac
	}
	return ""
}

func (x *UserInfo) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *UserInfo) GetOS() string {
	if x != nil {
		return x.OS
	}
	return ""
}

func (x *UserInfo) GetNetMode() string {
	if x != nil {
		return x.NetMode
	}
	return ""
}

func (x *UserInfo) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *UserInfo) GetPhoneBrand() string {
	if x != nil {
		return x.PhoneBrand
	}
	return ""
}

func (x *UserInfo) GetNewPassword() string {
	if x != nil {
		return x.NewPassword
	}
	return ""
}

func (x *UserInfo) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *UserInfo) GetIDFA() string {
	if x != nil {
		return x.IDFA
	}
	return ""
}

func (x *UserInfo) GetSubId() int32 {
	if x != nil {
		return x.SubId
	}
	return 0
}

func (x *UserInfo) GetIP() string {
	if x != nil {
		return x.IP
	}
	return ""
}

func (x *UserInfo) GetIPLimit() int32 {
	if x != nil {
		return x.IPLimit
	}
	return 0
}

func (x *UserInfo) GetIPLimitPerDay() int32 {
	if x != nil {
		return x.IPLimitPerDay
	}
	return 0
}

func (x *UserInfo) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *UserInfo) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *UserInfo) GetCreateTime() string {
	if x != nil {
		return x.CreateTime
	}
	return ""
}

func (x *UserInfo) GetServerName() string {
	if x != nil {
		return x.ServerName
	}
	return ""
}

func (x *UserInfo) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UserInfo) GetPlateIcon() string {
	if x != nil {
		return x.PlateIcon
	}
	return ""
}

type TableConfig struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name    string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Content string `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	Version int32  `protobuf:"varint,3,opt,name=version,proto3" json:"version,omitempty"`
}

func (x *TableConfig) Reset() {
	*x = TableConfig{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_pb_global_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TableConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TableConfig) ProtoMessage() {}

func (x *TableConfig) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_global_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TableConfig.ProtoReflect.Descriptor instead.
func (*TableConfig) Descriptor() ([]byte, []int) {
	return file_internal_pb_global_proto_rawDescGZIP(), []int{1}
}

func (x *TableConfig) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TableConfig) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *TableConfig) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

type ScriptFile struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Body string `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`
}

func (x *ScriptFile) Reset() {
	*x = ScriptFile{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_pb_global_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ScriptFile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScriptFile) ProtoMessage() {}

func (x *ScriptFile) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_global_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScriptFile.ProtoReflect.Descriptor instead.
func (*ScriptFile) Descriptor() ([]byte, []int) {
	return file_internal_pb_global_proto_rawDescGZIP(), []int{2}
}

func (x *ScriptFile) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ScriptFile) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

type Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UId    int32  `protobuf:"varint,1,opt,name=UId,proto3" json:"UId,omitempty"`
	RoomId int32  `protobuf:"varint,2,opt,name=roomId,proto3" json:"roomId,omitempty"`
	Name   string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Data   string `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	Id     int32  `protobuf:"varint,5,opt,name=id,proto3" json:"id,omitempty"`
	Result int32  `protobuf:"varint,7,opt,name=result,proto3" json:"result,omitempty"`
	Type   int32  `protobuf:"varint,8,opt,name=type,proto3" json:"type,omitempty"`
	SubId  int32  `protobuf:"varint,9,opt,name=subId,proto3" json:"subId,omitempty"`
	Num    int32  `protobuf:"varint,10,opt,name=num,proto3" json:"num,omitempty"`
	Date   string `protobuf:"bytes,11,opt,name=Date,proto3" json:"Date,omitempty"`
	OpenId string `protobuf:"bytes,12,opt,name=OpenId,proto3" json:"OpenId,omitempty"`
}

func (x *Request) Reset() {
	*x = Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_pb_global_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request) ProtoMessage() {}

func (x *Request) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_global_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request.ProtoReflect.Descriptor instead.
func (*Request) Descriptor() ([]byte, []int) {
	return file_internal_pb_global_proto_rawDescGZIP(), []int{3}
}

func (x *Request) GetUId() int32 {
	if x != nil {
		return x.UId
	}
	return 0
}

func (x *Request) GetRoomId() int32 {
	if x != nil {
		return x.RoomId
	}
	return 0
}

func (x *Request) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Request) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

func (x *Request) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Request) GetResult() int32 {
	if x != nil {
		return x.Result
	}
	return 0
}

func (x *Request) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *Request) GetSubId() int32 {
	if x != nil {
		return x.SubId
	}
	return 0
}

func (x *Request) GetNum() int32 {
	if x != nil {
		return x.Num
	}
	return 0
}

func (x *Request) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *Request) GetOpenId() string {
	if x != nil {
		return x.OpenId
	}
	return ""
}

type Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code int32  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg  string `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Id   int64  `protobuf:"varint,3,opt,name=id,proto3" json:"id,omitempty"`
	Data string `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	UId  int32  `protobuf:"varint,5,opt,name=UId,proto3" json:"UId,omitempty"`
}

func (x *Response) Reset() {
	*x = Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_pb_global_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_global_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_internal_pb_global_proto_rawDescGZIP(), []int{4}
}

func (x *Response) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *Response) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *Response) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Response) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

func (x *Response) GetUId() int32 {
	if x != nil {
		return x.UId
	}
	return 0
}

type EnterGameReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UId   int32 `protobuf:"varint,1,opt,name=UId,proto3" json:"UId,omitempty"`
	SubId int32 `protobuf:"varint,2,opt,name=SubId,proto3" json:"SubId,omitempty"`
}

func (x *EnterGameReq) Reset() {
	*x = EnterGameReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_pb_global_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EnterGameReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnterGameReq) ProtoMessage() {}

func (x *EnterGameReq) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_global_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnterGameReq.ProtoReflect.Descriptor instead.
func (*EnterGameReq) Descriptor() ([]byte, []int) {
	return file_internal_pb_global_proto_rawDescGZIP(), []int{5}
}

func (x *EnterGameReq) GetUId() int32 {
	if x != nil {
		return x.UId
	}
	return 0
}

func (x *EnterGameReq) GetSubId() int32 {
	if x != nil {
		return x.SubId
	}
	return 0
}

type Notify struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Mails         int32 `protobuf:"varint,1,opt,name=Mails,proto3" json:"Mails,omitempty"`
	LongTimeCards int32 `protobuf:"varint,2,opt,name=LongTimeCards,proto3" json:"LongTimeCards,omitempty"` // 长线收集卡片
}

func (x *Notify) Reset() {
	*x = Notify{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_pb_global_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Notify) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Notify) ProtoMessage() {}

func (x *Notify) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_global_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Notify.ProtoReflect.Descriptor instead.
func (*Notify) Descriptor() ([]byte, []int) {
	return file_internal_pb_global_proto_rawDescGZIP(), []int{6}
}

func (x *Notify) GetMails() int32 {
	if x != nil {
		return x.Mails
	}
	return 0
}

func (x *Notify) GetLongTimeCards() int32 {
	if x != nil {
		return x.LongTimeCards
	}
	return 0
}

type EnterGameResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserInfo             *UserInfo    `protobuf:"bytes,1,opt,name=userInfo,proto3" json:"userInfo,omitempty"`
	Bin                  *UserBin     `protobuf:"bytes,11,opt,name=bin,proto3" json:"bin,omitempty"`
	LoginParams          *LoginParams `protobuf:"bytes,17,opt,name=LoginParams,proto3" json:"LoginParams,omitempty"`
	NewMailNum           int32        `protobuf:"varint,18,opt,name=NewMailNum,proto3" json:"NewMailNum,omitempty"`
	SubscriptionExpireTs int64        `protobuf:"varint,19,opt,name=SubscriptionExpireTs,proto3" json:"SubscriptionExpireTs,omitempty"` // 订阅过期时间
	GoogleAdName         string       `protobuf:"bytes,20,opt,name=GoogleAdName,proto3" json:"GoogleAdName,omitempty"`
}

func (x *EnterGameResp) Reset() {
	*x = EnterGameResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_pb_global_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EnterGameResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnterGameResp) ProtoMessage() {}

func (x *EnterGameResp) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_global_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnterGameResp.ProtoReflect.Descriptor instead.
func (*EnterGameResp) Descriptor() ([]byte, []int) {
	return file_internal_pb_global_proto_rawDescGZIP(), []int{7}
}

func (x *EnterGameResp) GetUserInfo() *UserInfo {
	if x != nil {
		return x.UserInfo
	}
	return nil
}

func (x *EnterGameResp) GetBin() *UserBin {
	if x != nil {
		return x.Bin
	}
	return nil
}

func (x *EnterGameResp) GetLoginParams() *LoginParams {
	if x != nil {
		return x.LoginParams
	}
	return nil
}

func (x *EnterGameResp) GetNewMailNum() int32 {
	if x != nil {
		return x.NewMailNum
	}
	return 0
}

func (x *EnterGameResp) GetSubscriptionExpireTs() int64 {
	if x != nil {
		return x.SubscriptionExpireTs
	}
	return 0
}

func (x *EnterGameResp) GetGoogleAdName() string {
	if x != nil {
		return x.GoogleAdName
	}
	return ""
}

type AuthReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UId int32  `protobuf:"varint,1,opt,name=UId,proto3" json:"UId,omitempty"`
	IP  string `protobuf:"bytes,2,opt,name=IP,proto3" json:"IP,omitempty"`
}

func (x *AuthReq) Reset() {
	*x = AuthReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_pb_global_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AuthReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthReq) ProtoMessage() {}

func (x *AuthReq) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_global_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthReq.ProtoReflect.Descriptor instead.
func (*AuthReq) Descriptor() ([]byte, []int) {
	return file_internal_pb_global_proto_rawDescGZIP(), []int{8}
}

func (x *AuthReq) GetUId() int32 {
	if x != nil {
		return x.UId
	}
	return 0
}

func (x *AuthReq) GetIP() string {
	if x != nil {
		return x.IP
	}
	return ""
}

type AuthResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Token         string   `protobuf:"bytes,1,opt,name=Token,proto3" json:"Token,omitempty"`
	Reason        int32    `protobuf:"varint,2,opt,name=Reason,proto3" json:"Reason,omitempty"`
	ClientVersion string   `protobuf:"bytes,5,opt,name=ClientVersion,proto3" json:"ClientVersion,omitempty"` // 版本
	LoginTime     string   `protobuf:"bytes,6,opt,name=LoginTime,proto3" json:"LoginTime,omitempty"`         // 登陆时间
	LoginPlates   []string `protobuf:"bytes,7,rep,name=LoginPlates,proto3" json:"LoginPlates,omitempty"`
	ServerName    string   `protobuf:"bytes,8,opt,name=ServerName,proto3" json:"ServerName,omitempty"`
}

func (x *AuthResp) Reset() {
	*x = AuthResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_pb_global_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AuthResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthResp) ProtoMessage() {}

func (x *AuthResp) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_global_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthResp.ProtoReflect.Descriptor instead.
func (*AuthResp) Descriptor() ([]byte, []int) {
	return file_internal_pb_global_proto_rawDescGZIP(), []int{9}
}

func (x *AuthResp) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *AuthResp) GetReason() int32 {
	if x != nil {
		return x.Reason
	}
	return 0
}

func (x *AuthResp) GetClientVersion() string {
	if x != nil {
		return x.ClientVersion
	}
	return ""
}

func (x *AuthResp) GetLoginTime() string {
	if x != nil {
		return x.LoginTime
	}
	return ""
}

func (x *AuthResp) GetLoginPlates() []string {
	if x != nil {
		return x.LoginPlates
	}
	return nil
}

func (x *AuthResp) GetServerName() string {
	if x != nil {
		return x.ServerName
	}
	return ""
}

type GlobalBin struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LastDayUpdateTs int64   `protobuf:"varint,1,opt,name=LastDayUpdateTs,proto3" json:"LastDayUpdateTs,omitempty"` // 每日数据上次更新时间
	Items           []*Item `protobuf:"bytes,2,rep,name=Items,proto3" json:"Items,omitempty"`                      // 物品
	Level           int32   `protobuf:"varint,3,opt,name=Level,proto3" json:"Level,omitempty"`                     // 等级
}

func (x *GlobalBin) Reset() {
	*x = GlobalBin{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_pb_global_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GlobalBin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GlobalBin) ProtoMessage() {}

func (x *GlobalBin) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_global_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GlobalBin.ProtoReflect.Descriptor instead.
func (*GlobalBin) Descriptor() ([]byte, []int) {
	return file_internal_pb_global_proto_rawDescGZIP(), []int{10}
}

func (x *GlobalBin) GetLastDayUpdateTs() int64 {
	if x != nil {
		return x.LastDayUpdateTs
	}
	return 0
}

func (x *GlobalBin) GetItems() []*Item {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *GlobalBin) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

// 离线物品待合并
type OfflineBin struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// int32 OfflineItemPos = 1; // 离线物品最大位移
	Items []*Item `protobuf:"bytes,2,rep,name=Items,proto3" json:"Items,omitempty"`
}

func (x *OfflineBin) Reset() {
	*x = OfflineBin{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_pb_global_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OfflineBin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OfflineBin) ProtoMessage() {}

func (x *OfflineBin) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_global_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OfflineBin.ProtoReflect.Descriptor instead.
func (*OfflineBin) Descriptor() ([]byte, []int) {
	return file_internal_pb_global_proto_rawDescGZIP(), []int{11}
}

func (x *OfflineBin) GetItems() []*Item {
	if x != nil {
		return x.Items
	}
	return nil
}

type UserBin struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Hall    *HallBin    `protobuf:"bytes,1,opt,name=Hall,proto3" json:"Hall,omitempty"`       //大厅数据
	Global  *GlobalBin  `protobuf:"bytes,2,opt,name=Global,proto3" json:"Global,omitempty"`   //全局数据
	Offline *OfflineBin `protobuf:"bytes,3,opt,name=Offline,proto3" json:"Offline,omitempty"` //离线数据，待合并数据
	Room    *RoomBin    `protobuf:"bytes,5,opt,name=Room,proto3" json:"Room,omitempty"`       //房间数据
	Stat    *StatBin    `protobuf:"bytes,6,opt,name=Stat,proto3" json:"Stat,omitempty"`       // 统计数据
}

func (x *UserBin) Reset() {
	*x = UserBin{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_pb_global_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserBin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserBin) ProtoMessage() {}

func (x *UserBin) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_global_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserBin.ProtoReflect.Descriptor instead.
func (*UserBin) Descriptor() ([]byte, []int) {
	return file_internal_pb_global_proto_rawDescGZIP(), []int{12}
}

func (x *UserBin) GetHall() *HallBin {
	if x != nil {
		return x.Hall
	}
	return nil
}

func (x *UserBin) GetGlobal() *GlobalBin {
	if x != nil {
		return x.Global
	}
	return nil
}

func (x *UserBin) GetOffline() *OfflineBin {
	if x != nil {
		return x.Offline
	}
	return nil
}

func (x *UserBin) GetRoom() *RoomBin {
	if x != nil {
		return x.Room
	}
	return nil
}

func (x *UserBin) GetStat() *StatBin {
	if x != nil {
		return x.Stat
	}
	return nil
}

type RoomBin struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *RoomBin) Reset() {
	*x = RoomBin{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_pb_global_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RoomBin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomBin) ProtoMessage() {}

func (x *RoomBin) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_global_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomBin.ProtoReflect.Descriptor instead.
func (*RoomBin) Descriptor() ([]byte, []int) {
	return file_internal_pb_global_proto_rawDescGZIP(), []int{13}
}

type SaveBinReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UId int32    `protobuf:"varint,1,opt,name=UId,proto3" json:"UId,omitempty"`
	Bin *UserBin `protobuf:"bytes,2,opt,name=Bin,proto3" json:"Bin,omitempty"`
}

func (x *SaveBinReq) Reset() {
	*x = SaveBinReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_pb_global_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SaveBinReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveBinReq) ProtoMessage() {}

func (x *SaveBinReq) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_global_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveBinReq.ProtoReflect.Descriptor instead.
func (*SaveBinReq) Descriptor() ([]byte, []int) {
	return file_internal_pb_global_proto_rawDescGZIP(), []int{14}
}

func (x *SaveBinReq) GetUId() int32 {
	if x != nil {
		return x.UId
	}
	return 0
}

func (x *SaveBinReq) GetBin() *UserBin {
	if x != nil {
		return x.Bin
	}
	return nil
}

type SubGame struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GameName   string `protobuf:"bytes,1,opt,name=gameName,proto3" json:"gameName,omitempty"`
	RoomName   string `protobuf:"bytes,2,opt,name=roomName,proto3" json:"roomName,omitempty"`
	Num        int32  `protobuf:"varint,3,opt,name=num,proto3" json:"num,omitempty"`
	Id         int32  `protobuf:"varint,4,opt,name=Id,proto3" json:"Id,omitempty"`
	ServerName string `protobuf:"bytes,5,opt,name=ServerName,proto3" json:"ServerName,omitempty"`
}

func (x *SubGame) Reset() {
	*x = SubGame{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_pb_global_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SubGame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubGame) ProtoMessage() {}

func (x *SubGame) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_global_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubGame.ProtoReflect.Descriptor instead.
func (*SubGame) Descriptor() ([]byte, []int) {
	return file_internal_pb_global_proto_rawDescGZIP(), []int{15}
}

func (x *SubGame) GetGameName() string {
	if x != nil {
		return x.GameName
	}
	return ""
}

func (x *SubGame) GetRoomName() string {
	if x != nil {
		return x.RoomName
	}
	return ""
}

func (x *SubGame) GetNum() int32 {
	if x != nil {
		return x.Num
	}
	return 0
}

func (x *SubGame) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *SubGame) GetServerName() string {
	if x != nil {
		return x.ServerName
	}
	return ""
}

type VisitReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UId        int32  `protobuf:"varint,1,opt,name=UId,proto3" json:"UId,omitempty"`
	SubId      int32  `protobuf:"varint,2,opt,name=SubId,proto3" json:"SubId,omitempty"`
	ServerName string `protobuf:"bytes,3,opt,name=ServerName,proto3" json:"ServerName,omitempty"`
}

func (x *VisitReq) Reset() {
	*x = VisitReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_pb_global_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VisitReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VisitReq) ProtoMessage() {}

func (x *VisitReq) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_global_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VisitReq.ProtoReflect.Descriptor instead.
func (*VisitReq) Descriptor() ([]byte, []int) {
	return file_internal_pb_global_proto_rawDescGZIP(), []int{16}
}

func (x *VisitReq) GetUId() int32 {
	if x != nil {
		return x.UId
	}
	return 0
}

func (x *VisitReq) GetSubId() int32 {
	if x != nil {
		return x.SubId
	}
	return 0
}

func (x *VisitReq) GetServerName() string {
	if x != nil {
		return x.ServerName
	}
	return ""
}

type ItemParams struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CardNum int32 `protobuf:"varint,1,opt,name=CardNum,proto3" json:"CardNum,omitempty"`
	Mode    int32 `protobuf:"varint,2,opt,name=Mode,proto3" json:"Mode,omitempty"`
	SubId   int32 `protobuf:"varint,3,opt,name=SubId,proto3" json:"SubId,omitempty"`
	OtherId int32 `protobuf:"varint,4,opt,name=OtherId,proto3" json:"OtherId,omitempty"`
	ShopId  int32 `protobuf:"varint,5,opt,name=ShopId,proto3" json:"ShopId,omitempty"`
	Round   int32 `protobuf:"varint,6,opt,name=Round,proto3" json:"Round,omitempty"`
}

func (x *ItemParams) Reset() {
	*x = ItemParams{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_pb_global_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ItemParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ItemParams) ProtoMessage() {}

func (x *ItemParams) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_global_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ItemParams.ProtoReflect.Descriptor instead.
func (*ItemParams) Descriptor() ([]byte, []int) {
	return file_internal_pb_global_proto_rawDescGZIP(), []int{17}
}

func (x *ItemParams) GetCardNum() int32 {
	if x != nil {
		return x.CardNum
	}
	return 0
}

func (x *ItemParams) GetMode() int32 {
	if x != nil {
		return x.Mode
	}
	return 0
}

func (x *ItemParams) GetSubId() int32 {
	if x != nil {
		return x.SubId
	}
	return 0
}

func (x *ItemParams) GetOtherId() int32 {
	if x != nil {
		return x.OtherId
	}
	return 0
}

func (x *ItemParams) GetShopId() int32 {
	if x != nil {
		return x.ShopId
	}
	return 0
}

func (x *ItemParams) GetRound() int32 {
	if x != nil {
		return x.Round
	}
	return 0
}

type ItemReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UId      int32       `protobuf:"varint,1,opt,name=UId,proto3" json:"UId,omitempty"`
	Way      string      `protobuf:"bytes,5,opt,name=Way,proto3" json:"Way,omitempty"`
	Uuid     string      `protobuf:"bytes,6,opt,name=Uuid,proto3" json:"Uuid,omitempty"`
	OtherId  int32       `protobuf:"varint,8,opt,name=OtherId,proto3" json:"OtherId,omitempty"`
	SubId    int32       `protobuf:"varint,9,opt,name=SubId,proto3" json:"SubId,omitempty"`
	Items    []*Item     `protobuf:"bytes,10,rep,name=Items,proto3" json:"Items,omitempty"`
	Params   *ItemParams `protobuf:"bytes,11,opt,name=Params,proto3" json:"Params,omitempty"`
	Deadline int64       `protobuf:"varint,12,opt,name=Deadline,proto3" json:"Deadline,omitempty"`
}

func (x *ItemReq) Reset() {
	*x = ItemReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_pb_global_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ItemReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ItemReq) ProtoMessage() {}

func (x *ItemReq) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_global_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ItemReq.ProtoReflect.Descriptor instead.
func (*ItemReq) Descriptor() ([]byte, []int) {
	return file_internal_pb_global_proto_rawDescGZIP(), []int{18}
}

func (x *ItemReq) GetUId() int32 {
	if x != nil {
		return x.UId
	}
	return 0
}

func (x *ItemReq) GetWay() string {
	if x != nil {
		return x.Way
	}
	return ""
}

func (x *ItemReq) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *ItemReq) GetOtherId() int32 {
	if x != nil {
		return x.OtherId
	}
	return 0
}

func (x *ItemReq) GetSubId() int32 {
	if x != nil {
		return x.SubId
	}
	return 0
}

func (x *ItemReq) GetItems() []*Item {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *ItemReq) GetParams() *ItemParams {
	if x != nil {
		return x.Params
	}
	return nil
}

func (x *ItemReq) GetDeadline() int64 {
	if x != nil {
		return x.Deadline
	}
	return 0
}

type DictValue struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key   string `protobuf:"bytes,1,opt,name=Key,proto3" json:"Key,omitempty"`
	Value string `protobuf:"bytes,2,opt,name=Value,proto3" json:"Value,omitempty"`
}

func (x *DictValue) Reset() {
	*x = DictValue{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_pb_global_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DictValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DictValue) ProtoMessage() {}

func (x *DictValue) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_global_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DictValue.ProtoReflect.Descriptor instead.
func (*DictValue) Descriptor() ([]byte, []int) {
	return file_internal_pb_global_proto_rawDescGZIP(), []int{19}
}

func (x *DictValue) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *DictValue) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type SignIn struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DrawState int32 `protobuf:"varint,7,opt,name=DrawState,proto3" json:"DrawState,omitempty"`
	DrawTs    int64 `protobuf:"varint,8,opt,name=DrawTs,proto3" json:"DrawTs,omitempty"`
}

func (x *SignIn) Reset() {
	*x = SignIn{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_pb_global_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SignIn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignIn) ProtoMessage() {}

func (x *SignIn) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_global_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignIn.ProtoReflect.Descriptor instead.
func (*SignIn) Descriptor() ([]byte, []int) {
	return file_internal_pb_global_proto_rawDescGZIP(), []int{20}
}

func (x *SignIn) GetDrawState() int32 {
	if x != nil {
		return x.DrawState
	}
	return 0
}

func (x *SignIn) GetDrawTs() int64 {
	if x != nil {
		return x.DrawTs
	}
	return 0
}

var File_internal_pb_global_proto protoreflect.FileDescriptor

var file_internal_pb_global_proto_rawDesc = []byte{
	0x0a, 0x18, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x70, 0x62, 0x2f, 0x67, 0x6c,
	0x6f, 0x62, 0x61, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70, 0x62, 0x1a, 0x17,
	0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x70, 0x62, 0x2f, 0x6c, 0x6f, 0x67, 0x69,
	0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x16, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61,
	0x6c, 0x2f, 0x70, 0x62, 0x2f, 0x68, 0x61, 0x6c, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a,
	0x18, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x70, 0x62, 0x2f, 0x63, 0x6f, 0x6d,
	0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x16, 0x69, 0x6e, 0x74, 0x65, 0x72,
	0x6e, 0x61, 0x6c, 0x2f, 0x70, 0x62, 0x2f, 0x73, 0x74, 0x61, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0xa2, 0x06, 0x0a, 0x08, 0x55, 0x73, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x10,
	0x0a, 0x03, 0x55, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x55, 0x49, 0x64,
	0x12, 0x12, 0x0a, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x4e, 0x61, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x18,
	0x0a, 0x07, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x50, 0x61, 0x73, 0x73,
	0x77, 0x6f, 0x72, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x50, 0x61, 0x73, 0x73,
	0x77, 0x6f, 0x72, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x50, 0x6c, 0x61, 0x74, 0x65, 0x18, 0x06, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x50, 0x6c, 0x61, 0x74, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x4f, 0x70,
	0x65, 0x6e, 0x49, 0x64, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x4f, 0x70, 0x65, 0x6e,
	0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x43, 0x68, 0x61, 0x6e, 0x49, 0x64, 0x18, 0x09, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x43, 0x68, 0x61, 0x6e, 0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x4e, 0x69,
	0x63, 0x6b, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x4e, 0x69,
	0x63, 0x6b, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x53, 0x65, 0x78, 0x18, 0x0b, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x03, 0x53, 0x65, 0x78, 0x12, 0x10, 0x0a, 0x03, 0x56, 0x49, 0x50, 0x18,
	0x0c, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x56, 0x49, 0x50, 0x12, 0x12, 0x0a, 0x04, 0x49, 0x63,
	0x6f, 0x6e, 0x18, 0x0d, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x49, 0x63, 0x6f, 0x6e, 0x12, 0x12,
	0x0a, 0x04, 0x49, 0x6d, 0x73, 0x69, 0x18, 0x0e, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x49, 0x6d,
	0x73, 0x69, 0x12, 0x12, 0x0a, 0x04, 0x49, 0x6d, 0x65, 0x69, 0x18, 0x0f, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x49, 0x6d, 0x65, 0x69, 0x12, 0x10, 0x0a, 0x03, 0x4d, 0x61, 0x63, 0x18, 0x10, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x03, 0x4d, 0x61, 0x63, 0x12, 0x14, 0x0a, 0x05, 0x50, 0x68, 0x6f, 0x6e,
	0x65, 0x18, 0x11, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x50, 0x68, 0x6f, 0x6e, 0x65, 0x12, 0x0e,
	0x0a, 0x02, 0x4f, 0x53, 0x18, 0x12, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x4f, 0x53, 0x12, 0x18,
	0x0a, 0x07, 0x4e, 0x65, 0x74, 0x4d, 0x6f, 0x64, 0x65, 0x18, 0x13, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x4e, 0x65, 0x74, 0x4d, 0x6f, 0x64, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x56, 0x65, 0x72, 0x73,
	0x69, 0x6f, 0x6e, 0x18, 0x14, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x56, 0x65, 0x72, 0x73, 0x69,
	0x6f, 0x6e, 0x12, 0x1e, 0x0a, 0x0a, 0x50, 0x68, 0x6f, 0x6e, 0x65, 0x42, 0x72, 0x61, 0x6e, 0x64,
	0x18, 0x15, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x50, 0x68, 0x6f, 0x6e, 0x65, 0x42, 0x72, 0x61,
	0x6e, 0x64, 0x12, 0x20, 0x0a, 0x0b, 0x4e, 0x65, 0x77, 0x50, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72,
	0x64, 0x18, 0x16, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x4e, 0x65, 0x77, 0x50, 0x61, 0x73, 0x73,
	0x77, 0x6f, 0x72, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x4d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x18, 0x17,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x4d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x12, 0x12, 0x0a, 0x04,
	0x49, 0x44, 0x46, 0x41, 0x18, 0x18, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x49, 0x44, 0x46, 0x41,
	0x12, 0x14, 0x0a, 0x05, 0x53, 0x75, 0x62, 0x49, 0x64, 0x18, 0x19, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x05, 0x53, 0x75, 0x62, 0x49, 0x64, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x50, 0x18, 0x1a, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x02, 0x49, 0x50, 0x12, 0x18, 0x0a, 0x07, 0x49, 0x50, 0x4c, 0x69, 0x6d, 0x69,
	0x74, 0x18, 0x1b, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x49, 0x50, 0x4c, 0x69, 0x6d, 0x69, 0x74,
	0x12, 0x24, 0x0a, 0x0d, 0x49, 0x50, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x50, 0x65, 0x72, 0x44, 0x61,
	0x79, 0x18, 0x1c, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0d, 0x49, 0x50, 0x4c, 0x69, 0x6d, 0x69, 0x74,
	0x50, 0x65, 0x72, 0x44, 0x61, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x18,
	0x1e, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x14, 0x0a, 0x05,
	0x4c, 0x65, 0x76, 0x65, 0x6c, 0x18, 0x1f, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x4c, 0x65, 0x76,
	0x65, 0x6c, 0x12, 0x1e, 0x0a, 0x0a, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65,
	0x18, 0x22, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x69,
	0x6d, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65,
	0x18, 0x23, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x4e, 0x61,
	0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x24, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x12, 0x1c, 0x0a, 0x09, 0x50, 0x6c, 0x61, 0x74,
	0x65, 0x49, 0x63, 0x6f, 0x6e, 0x18, 0x25, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x50, 0x6c, 0x61,
	0x74, 0x65, 0x49, 0x63, 0x6f, 0x6e, 0x22, 0x55, 0x0a, 0x0b, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x43,
	0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6e,
	0x74, 0x65, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74,
	0x65, 0x6e, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x22, 0x34, 0x0a,
	0x0a, 0x53, 0x63, 0x72, 0x69, 0x70, 0x74, 0x46, 0x69, 0x6c, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12,
	0x12, 0x0a, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x62,
	0x6f, 0x64, 0x79, 0x22, 0xeb, 0x01, 0x0a, 0x07, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x10, 0x0a, 0x03, 0x55, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x55, 0x49,
	0x64, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x6f, 0x6f, 0x6d, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x06, 0x72, 0x6f, 0x6f, 0x6d, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a,
	0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x64, 0x61, 0x74,
	0x61, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69,
	0x64, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x07, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70,
	0x65, 0x18, 0x08, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x14, 0x0a,
	0x05, 0x73, 0x75, 0x62, 0x49, 0x64, 0x18, 0x09, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x73, 0x75,
	0x62, 0x49, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x6e, 0x75, 0x6d, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x03, 0x6e, 0x75, 0x6d, 0x12, 0x12, 0x0a, 0x04, 0x44, 0x61, 0x74, 0x65, 0x18, 0x0b, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x44, 0x61, 0x74, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x4f, 0x70, 0x65,
	0x6e, 0x49, 0x64, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x4f, 0x70, 0x65, 0x6e, 0x49,
	0x64, 0x22, 0x66, 0x0a, 0x08, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a,
	0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x63, 0x6f, 0x64,
	0x65, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03,
	0x6d, 0x73, 0x67, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x12, 0x10, 0x0a, 0x03, 0x55, 0x49, 0x64, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x55, 0x49, 0x64, 0x22, 0x36, 0x0a, 0x0c, 0x45, 0x6e, 0x74,
	0x65, 0x72, 0x47, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x71, 0x12, 0x10, 0x0a, 0x03, 0x55, 0x49, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x55, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x53,
	0x75, 0x62, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x53, 0x75, 0x62, 0x49,
	0x64, 0x22, 0x44, 0x0a, 0x06, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x4d,
	0x61, 0x69, 0x6c, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x4d, 0x61, 0x69, 0x6c,
	0x73, 0x12, 0x24, 0x0a, 0x0d, 0x4c, 0x6f, 0x6e, 0x67, 0x54, 0x69, 0x6d, 0x65, 0x43, 0x61, 0x72,
	0x64, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0d, 0x4c, 0x6f, 0x6e, 0x67, 0x54, 0x69,
	0x6d, 0x65, 0x43, 0x61, 0x72, 0x64, 0x73, 0x22, 0x83, 0x02, 0x0a, 0x0d, 0x45, 0x6e, 0x74, 0x65,
	0x72, 0x47, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x73, 0x70, 0x12, 0x28, 0x0a, 0x08, 0x75, 0x73, 0x65,
	0x72, 0x49, 0x6e, 0x66, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x70, 0x62,
	0x2e, 0x55, 0x73, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x49,
	0x6e, 0x66, 0x6f, 0x12, 0x1d, 0x0a, 0x03, 0x62, 0x69, 0x6e, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x0b, 0x2e, 0x70, 0x62, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x42, 0x69, 0x6e, 0x52, 0x03, 0x62,
	0x69, 0x6e, 0x12, 0x31, 0x0a, 0x0b, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x50, 0x61, 0x72, 0x61, 0x6d,
	0x73, 0x18, 0x11, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x70, 0x62, 0x2e, 0x4c, 0x6f, 0x67,
	0x69, 0x6e, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x52, 0x0b, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x50,
	0x61, 0x72, 0x61, 0x6d, 0x73, 0x12, 0x1e, 0x0a, 0x0a, 0x4e, 0x65, 0x77, 0x4d, 0x61, 0x69, 0x6c,
	0x4e, 0x75, 0x6d, 0x18, 0x12, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x4e, 0x65, 0x77, 0x4d, 0x61,
	0x69, 0x6c, 0x4e, 0x75, 0x6d, 0x12, 0x32, 0x0a, 0x14, 0x53, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69,
	0x70, 0x74, 0x69, 0x6f, 0x6e, 0x45, 0x78, 0x70, 0x69, 0x72, 0x65, 0x54, 0x73, 0x18, 0x13, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x14, 0x53, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f,
	0x6e, 0x45, 0x78, 0x70, 0x69, 0x72, 0x65, 0x54, 0x73, 0x12, 0x22, 0x0a, 0x0c, 0x47, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x41, 0x64, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x14, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0c, 0x47, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x41, 0x64, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x2b, 0x0a,
	0x07, 0x41, 0x75, 0x74, 0x68, 0x52, 0x65, 0x71, 0x12, 0x10, 0x0a, 0x03, 0x55, 0x49, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x55, 0x49, 0x64, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x50,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x49, 0x50, 0x22, 0xbe, 0x01, 0x0a, 0x08, 0x41,
	0x75, 0x74, 0x68, 0x52, 0x65, 0x73, 0x70, 0x12, 0x14, 0x0a, 0x05, 0x54, 0x6f, 0x6b, 0x65, 0x6e,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x16, 0x0a,
	0x06, 0x52, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x52,
	0x65, 0x61, 0x73, 0x6f, 0x6e, 0x12, 0x24, 0x0a, 0x0d, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x56,
	0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x43, 0x6c,
	0x69, 0x65, 0x6e, 0x74, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x1c, 0x0a, 0x09, 0x4c,
	0x6f, 0x67, 0x69, 0x6e, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09,
	0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x4c, 0x6f, 0x67,
	0x69, 0x6e, 0x50, 0x6c, 0x61, 0x74, 0x65, 0x73, 0x18, 0x07, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0b,
	0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x50, 0x6c, 0x61, 0x74, 0x65, 0x73, 0x12, 0x1e, 0x0a, 0x0a, 0x53,
	0x65, 0x72, 0x76, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0a, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x6b, 0x0a, 0x09, 0x47,
	0x6c, 0x6f, 0x62, 0x61, 0x6c, 0x42, 0x69, 0x6e, 0x12, 0x28, 0x0a, 0x0f, 0x4c, 0x61, 0x73, 0x74,
	0x44, 0x61, 0x79, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x54, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x0f, 0x4c, 0x61, 0x73, 0x74, 0x44, 0x61, 0x79, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x54, 0x73, 0x12, 0x1e, 0x0a, 0x05, 0x49, 0x74, 0x65, 0x6d, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x08, 0x2e, 0x70, 0x62, 0x2e, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x05, 0x49, 0x74, 0x65,
	0x6d, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x05, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x22, 0x2c, 0x0a, 0x0a, 0x4f, 0x66, 0x66, 0x6c,
	0x69, 0x6e, 0x65, 0x42, 0x69, 0x6e, 0x12, 0x1e, 0x0a, 0x05, 0x49, 0x74, 0x65, 0x6d, 0x73, 0x18,
	0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x08, 0x2e, 0x70, 0x62, 0x2e, 0x49, 0x74, 0x65, 0x6d, 0x52,
	0x05, 0x49, 0x74, 0x65, 0x6d, 0x73, 0x22, 0xbd, 0x01, 0x0a, 0x07, 0x55, 0x73, 0x65, 0x72, 0x42,
	0x69, 0x6e, 0x12, 0x1f, 0x0a, 0x04, 0x48, 0x61, 0x6c, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x0b, 0x2e, 0x70, 0x62, 0x2e, 0x48, 0x61, 0x6c, 0x6c, 0x42, 0x69, 0x6e, 0x52, 0x04, 0x48,
	0x61, 0x6c, 0x6c, 0x12, 0x25, 0x0a, 0x06, 0x47, 0x6c, 0x6f, 0x62, 0x61, 0x6c, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x70, 0x62, 0x2e, 0x47, 0x6c, 0x6f, 0x62, 0x61, 0x6c, 0x42,
	0x69, 0x6e, 0x52, 0x06, 0x47, 0x6c, 0x6f, 0x62, 0x61, 0x6c, 0x12, 0x28, 0x0a, 0x07, 0x4f, 0x66,
	0x66, 0x6c, 0x69, 0x6e, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x70, 0x62,
	0x2e, 0x4f, 0x66, 0x66, 0x6c, 0x69, 0x6e, 0x65, 0x42, 0x69, 0x6e, 0x52, 0x07, 0x4f, 0x66, 0x66,
	0x6c, 0x69, 0x6e, 0x65, 0x12, 0x1f, 0x0a, 0x04, 0x52, 0x6f, 0x6f, 0x6d, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x70, 0x62, 0x2e, 0x52, 0x6f, 0x6f, 0x6d, 0x42, 0x69, 0x6e, 0x52,
	0x04, 0x52, 0x6f, 0x6f, 0x6d, 0x12, 0x1f, 0x0a, 0x04, 0x53, 0x74, 0x61, 0x74, 0x18, 0x06, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x70, 0x62, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x42, 0x69, 0x6e,
	0x52, 0x04, 0x53, 0x74, 0x61, 0x74, 0x22, 0x09, 0x0a, 0x07, 0x52, 0x6f, 0x6f, 0x6d, 0x42, 0x69,
	0x6e, 0x22, 0x3d, 0x0a, 0x0a, 0x53, 0x61, 0x76, 0x65, 0x42, 0x69, 0x6e, 0x52, 0x65, 0x71, 0x12,
	0x10, 0x0a, 0x03, 0x55, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x55, 0x49,
	0x64, 0x12, 0x1d, 0x0a, 0x03, 0x42, 0x69, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b,
	0x2e, 0x70, 0x62, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x42, 0x69, 0x6e, 0x52, 0x03, 0x42, 0x69, 0x6e,
	0x22, 0x83, 0x01, 0x0a, 0x07, 0x53, 0x75, 0x62, 0x47, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08,
	0x67, 0x61, 0x6d, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x67, 0x61, 0x6d, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x72, 0x6f, 0x6f, 0x6d,
	0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x72, 0x6f, 0x6f, 0x6d,
	0x4e, 0x61, 0x6d, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6e, 0x75, 0x6d, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x03, 0x6e, 0x75, 0x6d, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x64, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x02, 0x49, 0x64, 0x12, 0x1e, 0x0a, 0x0a, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72,
	0x4e, 0x61, 0x6d, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x53, 0x65, 0x72, 0x76,
	0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x52, 0x0a, 0x08, 0x56, 0x69, 0x73, 0x69, 0x74, 0x52,
	0x65, 0x71, 0x12, 0x10, 0x0a, 0x03, 0x55, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x03, 0x55, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x53, 0x75, 0x62, 0x49, 0x64, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x05, 0x53, 0x75, 0x62, 0x49, 0x64, 0x12, 0x1e, 0x0a, 0x0a, 0x53, 0x65,
	0x72, 0x76, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a,
	0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x98, 0x01, 0x0a, 0x0a, 0x49,
	0x74, 0x65, 0x6d, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x43, 0x61, 0x72,
	0x64, 0x4e, 0x75, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x43, 0x61, 0x72, 0x64,
	0x4e, 0x75, 0x6d, 0x12, 0x12, 0x0a, 0x04, 0x4d, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x04, 0x4d, 0x6f, 0x64, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x53, 0x75, 0x62, 0x49, 0x64,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x53, 0x75, 0x62, 0x49, 0x64, 0x12, 0x18, 0x0a,
	0x07, 0x4f, 0x74, 0x68, 0x65, 0x72, 0x49, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07,
	0x4f, 0x74, 0x68, 0x65, 0x72, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x53, 0x68, 0x6f, 0x70, 0x49,
	0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x53, 0x68, 0x6f, 0x70, 0x49, 0x64, 0x12,
	0x14, 0x0a, 0x05, 0x52, 0x6f, 0x75, 0x6e, 0x64, 0x18, 0x06, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05,
	0x52, 0x6f, 0x75, 0x6e, 0x64, 0x22, 0xd5, 0x01, 0x0a, 0x07, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x65,
	0x71, 0x12, 0x10, 0x0a, 0x03, 0x55, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03,
	0x55, 0x49, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x57, 0x61, 0x79, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x03, 0x57, 0x61, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x55, 0x75, 0x69, 0x64, 0x18, 0x06, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x55, 0x75, 0x69, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x4f, 0x74, 0x68,
	0x65, 0x72, 0x49, 0x64, 0x18, 0x08, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x4f, 0x74, 0x68, 0x65,
	0x72, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x53, 0x75, 0x62, 0x49, 0x64, 0x18, 0x09, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x05, 0x53, 0x75, 0x62, 0x49, 0x64, 0x12, 0x1e, 0x0a, 0x05, 0x49, 0x74, 0x65,
	0x6d, 0x73, 0x18, 0x0a, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x08, 0x2e, 0x70, 0x62, 0x2e, 0x49, 0x74,
	0x65, 0x6d, 0x52, 0x05, 0x49, 0x74, 0x65, 0x6d, 0x73, 0x12, 0x26, 0x0a, 0x06, 0x50, 0x61, 0x72,
	0x61, 0x6d, 0x73, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x70, 0x62, 0x2e, 0x49,
	0x74, 0x65, 0x6d, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x52, 0x06, 0x50, 0x61, 0x72, 0x61, 0x6d,
	0x73, 0x12, 0x1a, 0x0a, 0x08, 0x44, 0x65, 0x61, 0x64, 0x6c, 0x69, 0x6e, 0x65, 0x18, 0x0c, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x08, 0x44, 0x65, 0x61, 0x64, 0x6c, 0x69, 0x6e, 0x65, 0x22, 0x33, 0x0a,
	0x09, 0x44, 0x69, 0x63, 0x74, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x4b, 0x65,
	0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x4b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05,
	0x56, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x56, 0x61, 0x6c,
	0x75, 0x65, 0x22, 0x3e, 0x0a, 0x06, 0x53, 0x69, 0x67, 0x6e, 0x49, 0x6e, 0x12, 0x1c, 0x0a, 0x09,
	0x44, 0x72, 0x61, 0x77, 0x53, 0x74, 0x61, 0x74, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x09, 0x44, 0x72, 0x61, 0x77, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x44, 0x72,
	0x61, 0x77, 0x54, 0x73, 0x18, 0x08, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x44, 0x72, 0x61, 0x77,
	0x54, 0x73, 0x42, 0x06, 0x5a, 0x04, 0x2e, 0x3b, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_internal_pb_global_proto_rawDescOnce sync.Once
	file_internal_pb_global_proto_rawDescData = file_internal_pb_global_proto_rawDesc
)

func file_internal_pb_global_proto_rawDescGZIP() []byte {
	file_internal_pb_global_proto_rawDescOnce.Do(func() {
		file_internal_pb_global_proto_rawDescData = protoimpl.X.CompressGZIP(file_internal_pb_global_proto_rawDescData)
	})
	return file_internal_pb_global_proto_rawDescData
}

var file_internal_pb_global_proto_msgTypes = make([]protoimpl.MessageInfo, 21)
var file_internal_pb_global_proto_goTypes = []interface{}{
	(*UserInfo)(nil),      // 0: pb.UserInfo
	(*TableConfig)(nil),   // 1: pb.TableConfig
	(*ScriptFile)(nil),    // 2: pb.ScriptFile
	(*Request)(nil),       // 3: pb.Request
	(*Response)(nil),      // 4: pb.Response
	(*EnterGameReq)(nil),  // 5: pb.EnterGameReq
	(*Notify)(nil),        // 6: pb.Notify
	(*EnterGameResp)(nil), // 7: pb.EnterGameResp
	(*AuthReq)(nil),       // 8: pb.AuthReq
	(*AuthResp)(nil),      // 9: pb.AuthResp
	(*GlobalBin)(nil),     // 10: pb.GlobalBin
	(*OfflineBin)(nil),    // 11: pb.OfflineBin
	(*UserBin)(nil),       // 12: pb.UserBin
	(*RoomBin)(nil),       // 13: pb.RoomBin
	(*SaveBinReq)(nil),    // 14: pb.SaveBinReq
	(*SubGame)(nil),       // 15: pb.SubGame
	(*VisitReq)(nil),      // 16: pb.VisitReq
	(*ItemParams)(nil),    // 17: pb.ItemParams
	(*ItemReq)(nil),       // 18: pb.ItemReq
	(*DictValue)(nil),     // 19: pb.DictValue
	(*SignIn)(nil),        // 20: pb.SignIn
	(*LoginParams)(nil),   // 21: pb.LoginParams
	(*Item)(nil),          // 22: pb.Item
	(*HallBin)(nil),       // 23: pb.HallBin
	(*StatBin)(nil),       // 24: pb.StatBin
}
var file_internal_pb_global_proto_depIdxs = []int32{
	0,  // 0: pb.EnterGameResp.userInfo:type_name -> pb.UserInfo
	12, // 1: pb.EnterGameResp.bin:type_name -> pb.UserBin
	21, // 2: pb.EnterGameResp.LoginParams:type_name -> pb.LoginParams
	22, // 3: pb.GlobalBin.Items:type_name -> pb.Item
	22, // 4: pb.OfflineBin.Items:type_name -> pb.Item
	23, // 5: pb.UserBin.Hall:type_name -> pb.HallBin
	10, // 6: pb.UserBin.Global:type_name -> pb.GlobalBin
	11, // 7: pb.UserBin.Offline:type_name -> pb.OfflineBin
	13, // 8: pb.UserBin.Room:type_name -> pb.RoomBin
	24, // 9: pb.UserBin.Stat:type_name -> pb.StatBin
	12, // 10: pb.SaveBinReq.Bin:type_name -> pb.UserBin
	22, // 11: pb.ItemReq.Items:type_name -> pb.Item
	17, // 12: pb.ItemReq.Params:type_name -> pb.ItemParams
	13, // [13:13] is the sub-list for method output_type
	13, // [13:13] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_internal_pb_global_proto_init() }
func file_internal_pb_global_proto_init() {
	if File_internal_pb_global_proto != nil {
		return
	}
	file_internal_pb_login_proto_init()
	file_internal_pb_hall_proto_init()
	file_internal_pb_common_proto_init()
	file_internal_pb_stat_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_internal_pb_global_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_pb_global_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TableConfig); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_pb_global_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ScriptFile); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_pb_global_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_pb_global_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_pb_global_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EnterGameReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_pb_global_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Notify); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_pb_global_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EnterGameResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_pb_global_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AuthReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_pb_global_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AuthResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_pb_global_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GlobalBin); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_pb_global_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OfflineBin); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_pb_global_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserBin); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_pb_global_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RoomBin); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_pb_global_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SaveBinReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_pb_global_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SubGame); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_pb_global_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VisitReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_pb_global_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ItemParams); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_pb_global_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ItemReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_pb_global_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DictValue); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_pb_global_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SignIn); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_internal_pb_global_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   21,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_pb_global_proto_goTypes,
		DependencyIndexes: file_internal_pb_global_proto_depIdxs,
		MessageInfos:      file_internal_pb_global_proto_msgTypes,
	}.Build()
	File_internal_pb_global_proto = out.File
	file_internal_pb_global_proto_rawDesc = nil
	file_internal_pb_global_proto_goTypes = nil
	file_internal_pb_global_proto_depIdxs = nil
}
