// 大厅

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.25.1
// source: internal/pb/hall.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 大厅的数据
type HallBin struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LastLandId           int32   `protobuf:"varint,2,opt,name=LastLandId,proto3" json:"LastLandId,omitempty"`
	LoginClientVersion   string  `protobuf:"bytes,4,opt,name=LoginClientVersion,proto3" json:"LoginClientVersion,omitempty"` // 上次登陆的版本
	BuildLevel           int32   `protobuf:"varint,5,opt,name=BuildLevel,proto3" json:"BuildLevel,omitempty"`                //建设度
	MaxBuildLevel        int32   `protobuf:"varint,6,opt,name=MaxBuildLevel,proto3" json:"MaxBuildLevel,omitempty"`          //玩家曾经抵达过的最大的建设度
	LastMassMail         int64   `protobuf:"varint,10,opt,name=LastMassMail,proto3" json:"LastMassMail,omitempty"`
	ActivityRoomExpireTs int64   `protobuf:"varint,11,opt,name=ActivityRoomExpireTs,proto3" json:"ActivityRoomExpireTs,omitempty"`
	ActivityRoomList     []int32 `protobuf:"varint,12,rep,packed,name=ActivityRoomList,proto3" json:"ActivityRoomList,omitempty"`
}

func (x *HallBin) Reset() {
	*x = HallBin{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_pb_hall_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HallBin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HallBin) ProtoMessage() {}

func (x *HallBin) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_hall_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HallBin.ProtoReflect.Descriptor instead.
func (*HallBin) Descriptor() ([]byte, []int) {
	return file_internal_pb_hall_proto_rawDescGZIP(), []int{0}
}

func (x *HallBin) GetLastLandId() int32 {
	if x != nil {
		return x.LastLandId
	}
	return 0
}

func (x *HallBin) GetLoginClientVersion() string {
	if x != nil {
		return x.LoginClientVersion
	}
	return ""
}

func (x *HallBin) GetBuildLevel() int32 {
	if x != nil {
		return x.BuildLevel
	}
	return 0
}

func (x *HallBin) GetMaxBuildLevel() int32 {
	if x != nil {
		return x.MaxBuildLevel
	}
	return 0
}

func (x *HallBin) GetLastMassMail() int64 {
	if x != nil {
		return x.LastMassMail
	}
	return 0
}

func (x *HallBin) GetActivityRoomExpireTs() int64 {
	if x != nil {
		return x.ActivityRoomExpireTs
	}
	return 0
}

func (x *HallBin) GetActivityRoomList() []int32 {
	if x != nil {
		return x.ActivityRoomList
	}
	return nil
}

type ClientVersion struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 版本 1.12.123.1234_r,1.12.123.1234_d,1.12.123.1234
	Version string `protobuf:"bytes,1,opt,name=Version,proto3" json:"Version,omitempty"`
	// 奖励 [[1102,1000],[1104,2000]]
	Reward  string    `protobuf:"bytes,2,opt,name=Reward,proto3" json:"Reward,omitempty"`
	ChanId  string    `protobuf:"bytes,3,opt,name=ChanId,proto3" json:"ChanId,omitempty"`
	Title   string    `protobuf:"bytes,4,opt,name=Title,proto3" json:"Title,omitempty"`
	Body    string    `protobuf:"bytes,5,opt,name=Body,proto3" json:"Body,omitempty"`
	Type    string    `protobuf:"bytes,6,opt,name=Type,proto3" json:"Type,omitempty"`
	Uid     int32     `protobuf:"varint,7,opt,name=Uid,proto3" json:"Uid,omitempty"`
	Bundles []*Bundle `protobuf:"bytes,8,rep,name=Bundles,proto3" json:"Bundles,omitempty"`
}

func (x *ClientVersion) Reset() {
	*x = ClientVersion{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_pb_hall_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClientVersion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientVersion) ProtoMessage() {}

func (x *ClientVersion) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_hall_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientVersion.ProtoReflect.Descriptor instead.
func (*ClientVersion) Descriptor() ([]byte, []int) {
	return file_internal_pb_hall_proto_rawDescGZIP(), []int{1}
}

func (x *ClientVersion) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *ClientVersion) GetReward() string {
	if x != nil {
		return x.Reward
	}
	return ""
}

func (x *ClientVersion) GetChanId() string {
	if x != nil {
		return x.ChanId
	}
	return ""
}

func (x *ClientVersion) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *ClientVersion) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *ClientVersion) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ClientVersion) GetUid() int32 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *ClientVersion) GetBundles() []*Bundle {
	if x != nil {
		return x.Bundles
	}
	return nil
}

type ClientVersionResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	List []*ClientVersion `protobuf:"bytes,1,rep,name=List,proto3" json:"List,omitempty"`
}

func (x *ClientVersionResp) Reset() {
	*x = ClientVersionResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_pb_hall_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClientVersionResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientVersionResp) ProtoMessage() {}

func (x *ClientVersionResp) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_hall_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientVersionResp.ProtoReflect.Descriptor instead.
func (*ClientVersionResp) Descriptor() ([]byte, []int) {
	return file_internal_pb_hall_proto_rawDescGZIP(), []int{2}
}

func (x *ClientVersionResp) GetList() []*ClientVersion {
	if x != nil {
		return x.List
	}
	return nil
}

type Mail struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id            int64    `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Type          int32    `protobuf:"varint,2,opt,name=Type,proto3" json:"Type,omitempty"`
	SendId        int32    `protobuf:"varint,3,opt,name=SendId,proto3" json:"SendId,omitempty"`
	RecvId        int32    `protobuf:"varint,4,opt,name=RecvId,proto3" json:"RecvId,omitempty"`
	Title         string   `protobuf:"bytes,5,opt,name=Title,proto3" json:"Title,omitempty"`
	Body          string   `protobuf:"bytes,6,opt,name=Body,proto3" json:"Body,omitempty"`
	Reward        string   `protobuf:"bytes,7,opt,name=Reward,proto3" json:"Reward,omitempty"`
	Status        int32    `protobuf:"varint,8,opt,name=Status,proto3" json:"Status,omitempty"`
	SendTime      string   `protobuf:"bytes,9,opt,name=SendTime,proto3" json:"SendTime,omitempty"`
	EffectTime    []string `protobuf:"bytes,10,rep,name=EffectTime,proto3" json:"EffectTime,omitempty"`
	RegTime       []string `protobuf:"bytes,11,rep,name=RegTime,proto3" json:"RegTime,omitempty"`
	LoginTime     []string `protobuf:"bytes,12,rep,name=LoginTime,proto3" json:"LoginTime,omitempty"`
	ClientVersion string   `protobuf:"bytes,13,opt,name=ClientVersion,proto3" json:"ClientVersion,omitempty"`
}

func (x *Mail) Reset() {
	*x = Mail{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_pb_hall_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Mail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Mail) ProtoMessage() {}

func (x *Mail) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_hall_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Mail.ProtoReflect.Descriptor instead.
func (*Mail) Descriptor() ([]byte, []int) {
	return file_internal_pb_hall_proto_rawDescGZIP(), []int{3}
}

func (x *Mail) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Mail) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *Mail) GetSendId() int32 {
	if x != nil {
		return x.SendId
	}
	return 0
}

func (x *Mail) GetRecvId() int32 {
	if x != nil {
		return x.RecvId
	}
	return 0
}

func (x *Mail) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Mail) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *Mail) GetReward() string {
	if x != nil {
		return x.Reward
	}
	return ""
}

func (x *Mail) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *Mail) GetSendTime() string {
	if x != nil {
		return x.SendTime
	}
	return ""
}

func (x *Mail) GetEffectTime() []string {
	if x != nil {
		return x.EffectTime
	}
	return nil
}

func (x *Mail) GetRegTime() []string {
	if x != nil {
		return x.RegTime
	}
	return nil
}

func (x *Mail) GetLoginTime() []string {
	if x != nil {
		return x.LoginTime
	}
	return nil
}

func (x *Mail) GetClientVersion() string {
	if x != nil {
		return x.ClientVersion
	}
	return ""
}

type MailReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id     int64 `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Type   int32 `protobuf:"varint,2,opt,name=Type,proto3" json:"Type,omitempty"`
	RecvId int32 `protobuf:"varint,3,opt,name=RecvId,proto3" json:"RecvId,omitempty"`
	Num    int32 `protobuf:"varint,4,opt,name=Num,proto3" json:"Num,omitempty"`
	Mail   *Mail `protobuf:"bytes,5,opt,name=Mail,proto3" json:"Mail,omitempty"`
	Status int32 `protobuf:"varint,6,opt,name=Status,proto3" json:"Status,omitempty"`
}

func (x *MailReq) Reset() {
	*x = MailReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_pb_hall_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MailReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MailReq) ProtoMessage() {}

func (x *MailReq) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_hall_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MailReq.ProtoReflect.Descriptor instead.
func (*MailReq) Descriptor() ([]byte, []int) {
	return file_internal_pb_hall_proto_rawDescGZIP(), []int{4}
}

func (x *MailReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *MailReq) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *MailReq) GetRecvId() int32 {
	if x != nil {
		return x.RecvId
	}
	return 0
}

func (x *MailReq) GetNum() int32 {
	if x != nil {
		return x.Num
	}
	return 0
}

func (x *MailReq) GetMail() *Mail {
	if x != nil {
		return x.Mail
	}
	return nil
}

func (x *MailReq) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

type MailResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   int64   `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Mail *Mail   `protobuf:"bytes,2,opt,name=Mail,proto3" json:"Mail,omitempty"`
	List []*Mail `protobuf:"bytes,3,rep,name=List,proto3" json:"List,omitempty"`
}

func (x *MailResp) Reset() {
	*x = MailResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_pb_hall_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MailResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MailResp) ProtoMessage() {}

func (x *MailResp) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_hall_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MailResp.ProtoReflect.Descriptor instead.
func (*MailResp) Descriptor() ([]byte, []int) {
	return file_internal_pb_hall_proto_rawDescGZIP(), []int{5}
}

func (x *MailResp) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *MailResp) GetMail() *Mail {
	if x != nil {
		return x.Mail
	}
	return nil
}

func (x *MailResp) GetList() []*Mail {
	if x != nil {
		return x.List
	}
	return nil
}

type BindAccountResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UId    int32    `protobuf:"varint,1,opt,name=UId,proto3" json:"UId,omitempty"`
	Plates []string `protobuf:"bytes,2,rep,name=Plates,proto3" json:"Plates,omitempty"`
}

func (x *BindAccountResp) Reset() {
	*x = BindAccountResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_pb_hall_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BindAccountResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BindAccountResp) ProtoMessage() {}

func (x *BindAccountResp) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_hall_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BindAccountResp.ProtoReflect.Descriptor instead.
func (*BindAccountResp) Descriptor() ([]byte, []int) {
	return file_internal_pb_hall_proto_rawDescGZIP(), []int{6}
}

func (x *BindAccountResp) GetUId() int32 {
	if x != nil {
		return x.UId
	}
	return 0
}

func (x *BindAccountResp) GetPlates() []string {
	if x != nil {
		return x.Plates
	}
	return nil
}

type EditableUserInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UId      int32  `protobuf:"varint,1,opt,name=UId,proto3" json:"UId,omitempty"`
	Nickname string `protobuf:"bytes,2,opt,name=Nickname,proto3" json:"Nickname,omitempty"`
	Icon     string `protobuf:"bytes,3,opt,name=Icon,proto3" json:"Icon,omitempty"`
	VIP      int32  `protobuf:"varint,4,opt,name=VIP,proto3" json:"VIP,omitempty"`
	Sex      int32  `protobuf:"varint,5,opt,name=Sex,proto3" json:"Sex,omitempty"`
	Email    string `protobuf:"bytes,6,opt,name=Email,proto3" json:"Email,omitempty"`
}

func (x *EditableUserInfo) Reset() {
	*x = EditableUserInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_pb_hall_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EditableUserInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EditableUserInfo) ProtoMessage() {}

func (x *EditableUserInfo) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_hall_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EditableUserInfo.ProtoReflect.Descriptor instead.
func (*EditableUserInfo) Descriptor() ([]byte, []int) {
	return file_internal_pb_hall_proto_rawDescGZIP(), []int{7}
}

func (x *EditableUserInfo) GetUId() int32 {
	if x != nil {
		return x.UId
	}
	return 0
}

func (x *EditableUserInfo) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *EditableUserInfo) GetIcon() string {
	if x != nil {
		return x.Icon
	}
	return ""
}

func (x *EditableUserInfo) GetVIP() int32 {
	if x != nil {
		return x.VIP
	}
	return 0
}

func (x *EditableUserInfo) GetSex() int32 {
	if x != nil {
		return x.Sex
	}
	return 0
}

func (x *EditableUserInfo) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

var File_internal_pb_hall_proto protoreflect.FileDescriptor

var file_internal_pb_hall_proto_rawDesc = []byte{
	0x0a, 0x16, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x70, 0x62, 0x2f, 0x68, 0x61,
	0x6c, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70, 0x62, 0x1a, 0x18, 0x69, 0x6e,
	0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x70, 0x62, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xa3, 0x02, 0x0a, 0x07, 0x48, 0x61, 0x6c, 0x6c, 0x42,
	0x69, 0x6e, 0x12, 0x1e, 0x0a, 0x0a, 0x4c, 0x61, 0x73, 0x74, 0x4c, 0x61, 0x6e, 0x64, 0x49, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x4c, 0x61, 0x73, 0x74, 0x4c, 0x61, 0x6e, 0x64,
	0x49, 0x64, 0x12, 0x2e, 0x0a, 0x12, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x43, 0x6c, 0x69, 0x65, 0x6e,
	0x74, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x12,
	0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x56, 0x65, 0x72, 0x73, 0x69,
	0x6f, 0x6e, 0x12, 0x1e, 0x0a, 0x0a, 0x42, 0x75, 0x69, 0x6c, 0x64, 0x4c, 0x65, 0x76, 0x65, 0x6c,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x42, 0x75, 0x69, 0x6c, 0x64, 0x4c, 0x65, 0x76,
	0x65, 0x6c, 0x12, 0x24, 0x0a, 0x0d, 0x4d, 0x61, 0x78, 0x42, 0x75, 0x69, 0x6c, 0x64, 0x4c, 0x65,
	0x76, 0x65, 0x6c, 0x18, 0x06, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0d, 0x4d, 0x61, 0x78, 0x42, 0x75,
	0x69, 0x6c, 0x64, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x12, 0x22, 0x0a, 0x0c, 0x4c, 0x61, 0x73, 0x74,
	0x4d, 0x61, 0x73, 0x73, 0x4d, 0x61, 0x69, 0x6c, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0c,
	0x4c, 0x61, 0x73, 0x74, 0x4d, 0x61, 0x73, 0x73, 0x4d, 0x61, 0x69, 0x6c, 0x12, 0x32, 0x0a, 0x14,
	0x41, 0x63, 0x74, 0x69, 0x76, 0x69, 0x74, 0x79, 0x52, 0x6f, 0x6f, 0x6d, 0x45, 0x78, 0x70, 0x69,
	0x72, 0x65, 0x54, 0x73, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x03, 0x52, 0x14, 0x41, 0x63, 0x74, 0x69,
	0x76, 0x69, 0x74, 0x79, 0x52, 0x6f, 0x6f, 0x6d, 0x45, 0x78, 0x70, 0x69, 0x72, 0x65, 0x54, 0x73,
	0x12, 0x2a, 0x0a, 0x10, 0x41, 0x63, 0x74, 0x69, 0x76, 0x69, 0x74, 0x79, 0x52, 0x6f, 0x6f, 0x6d,
	0x4c, 0x69, 0x73, 0x74, 0x18, 0x0c, 0x20, 0x03, 0x28, 0x05, 0x52, 0x10, 0x41, 0x63, 0x74, 0x69,
	0x76, 0x69, 0x74, 0x79, 0x52, 0x6f, 0x6f, 0x6d, 0x4c, 0x69, 0x73, 0x74, 0x22, 0xcf, 0x01, 0x0a,
	0x0d, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x18,
	0x0a, 0x07, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x16, 0x0a, 0x06, 0x52, 0x65, 0x77, 0x61,
	0x72, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x52, 0x65, 0x77, 0x61, 0x72, 0x64,
	0x12, 0x16, 0x0a, 0x06, 0x43, 0x68, 0x61, 0x6e, 0x49, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x43, 0x68, 0x61, 0x6e, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x54, 0x69, 0x74, 0x6c,
	0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x54, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x12,
	0x0a, 0x04, 0x42, 0x6f, 0x64, 0x79, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x42, 0x6f,
	0x64, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x54, 0x79, 0x70, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x54, 0x79, 0x70, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x55, 0x69, 0x64, 0x18, 0x07, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x03, 0x55, 0x69, 0x64, 0x12, 0x24, 0x0a, 0x07, 0x42, 0x75, 0x6e, 0x64,
	0x6c, 0x65, 0x73, 0x18, 0x08, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x70, 0x62, 0x2e, 0x42,
	0x75, 0x6e, 0x64, 0x6c, 0x65, 0x52, 0x07, 0x42, 0x75, 0x6e, 0x64, 0x6c, 0x65, 0x73, 0x22, 0x3a,
	0x0a, 0x11, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x52,
	0x65, 0x73, 0x70, 0x12, 0x25, 0x0a, 0x04, 0x4c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x11, 0x2e, 0x70, 0x62, 0x2e, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x56, 0x65, 0x72,
	0x73, 0x69, 0x6f, 0x6e, 0x52, 0x04, 0x4c, 0x69, 0x73, 0x74, 0x22, 0xce, 0x02, 0x0a, 0x04, 0x4d,
	0x61, 0x69, 0x6c, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x02, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x54, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x04, 0x54, 0x79, 0x70, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x53, 0x65, 0x6e, 0x64, 0x49,
	0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x53, 0x65, 0x6e, 0x64, 0x49, 0x64, 0x12,
	0x16, 0x0a, 0x06, 0x52, 0x65, 0x63, 0x76, 0x49, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x06, 0x52, 0x65, 0x63, 0x76, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x54, 0x69, 0x74, 0x6c, 0x65,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x54, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x12, 0x0a,
	0x04, 0x42, 0x6f, 0x64, 0x79, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x42, 0x6f, 0x64,
	0x79, 0x12, 0x16, 0x0a, 0x06, 0x52, 0x65, 0x77, 0x61, 0x72, 0x64, 0x18, 0x07, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x52, 0x65, 0x77, 0x61, 0x72, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x53, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x18, 0x08, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x12, 0x1a, 0x0a, 0x08, 0x53, 0x65, 0x6e, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x09, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x53, 0x65, 0x6e, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x1e, 0x0a,
	0x0a, 0x45, 0x66, 0x66, 0x65, 0x63, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x0a, 0x20, 0x03, 0x28,
	0x09, 0x52, 0x0a, 0x45, 0x66, 0x66, 0x65, 0x63, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x18, 0x0a,
	0x07, 0x52, 0x65, 0x67, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x0b, 0x20, 0x03, 0x28, 0x09, 0x52, 0x07,
	0x52, 0x65, 0x67, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x4c, 0x6f, 0x67, 0x69, 0x6e,
	0x54, 0x69, 0x6d, 0x65, 0x18, 0x0c, 0x20, 0x03, 0x28, 0x09, 0x52, 0x09, 0x4c, 0x6f, 0x67, 0x69,
	0x6e, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x24, 0x0a, 0x0d, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x56,
	0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x0d, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x43, 0x6c,
	0x69, 0x65, 0x6e, 0x74, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x22, 0x8d, 0x01, 0x0a, 0x07,
	0x4d, 0x61, 0x69, 0x6c, 0x52, 0x65, 0x71, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x02, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x54, 0x79, 0x70, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x54, 0x79, 0x70, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x52,
	0x65, 0x63, 0x76, 0x49, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x52, 0x65, 0x63,
	0x76, 0x49, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x4e, 0x75, 0x6d, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x03, 0x4e, 0x75, 0x6d, 0x12, 0x1c, 0x0a, 0x04, 0x4d, 0x61, 0x69, 0x6c, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x08, 0x2e, 0x70, 0x62, 0x2e, 0x4d, 0x61, 0x69, 0x6c, 0x52, 0x04, 0x4d,
	0x61, 0x69, 0x6c, 0x12, 0x16, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x06, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x56, 0x0a, 0x08, 0x4d,
	0x61, 0x69, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x02, 0x49, 0x64, 0x12, 0x1c, 0x0a, 0x04, 0x4d, 0x61, 0x69, 0x6c, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x08, 0x2e, 0x70, 0x62, 0x2e, 0x4d, 0x61, 0x69, 0x6c, 0x52,
	0x04, 0x4d, 0x61, 0x69, 0x6c, 0x12, 0x1c, 0x0a, 0x04, 0x4c, 0x69, 0x73, 0x74, 0x18, 0x03, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x08, 0x2e, 0x70, 0x62, 0x2e, 0x4d, 0x61, 0x69, 0x6c, 0x52, 0x04, 0x4c,
	0x69, 0x73, 0x74, 0x22, 0x3b, 0x0a, 0x0f, 0x42, 0x69, 0x6e, 0x64, 0x41, 0x63, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x12, 0x10, 0x0a, 0x03, 0x55, 0x49, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x03, 0x55, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x50, 0x6c, 0x61, 0x74,
	0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x06, 0x50, 0x6c, 0x61, 0x74, 0x65, 0x73,
	0x22, 0x8e, 0x01, 0x0a, 0x10, 0x45, 0x64, 0x69, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x55, 0x73, 0x65,
	0x72, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x10, 0x0a, 0x03, 0x55, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x03, 0x55, 0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x4e, 0x69, 0x63, 0x6b, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x4e, 0x69, 0x63, 0x6b, 0x6e,
	0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x49, 0x63, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x49, 0x63, 0x6f, 0x6e, 0x12, 0x10, 0x0a, 0x03, 0x56, 0x49, 0x50, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x56, 0x49, 0x50, 0x12, 0x10, 0x0a, 0x03, 0x53, 0x65, 0x78,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x53, 0x65, 0x78, 0x12, 0x14, 0x0a, 0x05, 0x45,
	0x6d, 0x61, 0x69, 0x6c, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x45, 0x6d, 0x61, 0x69,
	0x6c, 0x42, 0x06, 0x5a, 0x04, 0x2e, 0x3b, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_internal_pb_hall_proto_rawDescOnce sync.Once
	file_internal_pb_hall_proto_rawDescData = file_internal_pb_hall_proto_rawDesc
)

func file_internal_pb_hall_proto_rawDescGZIP() []byte {
	file_internal_pb_hall_proto_rawDescOnce.Do(func() {
		file_internal_pb_hall_proto_rawDescData = protoimpl.X.CompressGZIP(file_internal_pb_hall_proto_rawDescData)
	})
	return file_internal_pb_hall_proto_rawDescData
}

var file_internal_pb_hall_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_internal_pb_hall_proto_goTypes = []interface{}{
	(*HallBin)(nil),           // 0: pb.HallBin
	(*ClientVersion)(nil),     // 1: pb.ClientVersion
	(*ClientVersionResp)(nil), // 2: pb.ClientVersionResp
	(*Mail)(nil),              // 3: pb.Mail
	(*MailReq)(nil),           // 4: pb.MailReq
	(*MailResp)(nil),          // 5: pb.MailResp
	(*BindAccountResp)(nil),   // 6: pb.BindAccountResp
	(*EditableUserInfo)(nil),  // 7: pb.EditableUserInfo
	(*Bundle)(nil),            // 8: pb.Bundle
}
var file_internal_pb_hall_proto_depIdxs = []int32{
	8, // 0: pb.ClientVersion.Bundles:type_name -> pb.Bundle
	1, // 1: pb.ClientVersionResp.List:type_name -> pb.ClientVersion
	3, // 2: pb.MailReq.Mail:type_name -> pb.Mail
	3, // 3: pb.MailResp.Mail:type_name -> pb.Mail
	3, // 4: pb.MailResp.List:type_name -> pb.Mail
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_internal_pb_hall_proto_init() }
func file_internal_pb_hall_proto_init() {
	if File_internal_pb_hall_proto != nil {
		return
	}
	file_internal_pb_common_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_internal_pb_hall_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HallBin); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_pb_hall_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClientVersion); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_pb_hall_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClientVersionResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_pb_hall_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Mail); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_pb_hall_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MailReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_pb_hall_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MailResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_pb_hall_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BindAccountResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_pb_hall_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EditableUserInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_internal_pb_hall_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_pb_hall_proto_goTypes,
		DependencyIndexes: file_internal_pb_hall_proto_depIdxs,
		MessageInfos:      file_internal_pb_hall_proto_msgTypes,
	}.Build()
	File_internal_pb_hall_proto = out.File
	file_internal_pb_hall_proto_rawDesc = nil
	file_internal_pb_hall_proto_goTypes = nil
	file_internal_pb_hall_proto_depIdxs = nil
}
