// 登陆

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.25.1
// source: internal/pb/login.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 账号信息
type AccountInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UId         int32  `protobuf:"varint,1,opt,name=UId,proto3" json:"UId,omitempty"`
	Plate       string `protobuf:"bytes,2,opt,name=Plate,proto3" json:"Plate,omitempty"`
	OpenId      string `protobuf:"bytes,3,opt,name=OpenId,proto3" json:"OpenId,omitempty"`
	Method      string `protobuf:"bytes,4,opt,name=Method,proto3" json:"Method,omitempty"`
	NewPassword string `protobuf:"bytes,5,opt,name=NewPassword,proto3" json:"NewPassword,omitempty"`
	ChanId      string `protobuf:"bytes,9,opt,name=ChanId,proto3" json:"ChanId,omitempty"`
	Nickname    string `protobuf:"bytes,10,opt,name=Nickname,proto3" json:"Nickname,omitempty"`
	Sex         int32  `protobuf:"varint,11,opt,name=Sex,proto3" json:"Sex,omitempty"`
	Icon        string `protobuf:"bytes,13,opt,name=Icon,proto3" json:"Icon,omitempty"`
	Imsi        string `protobuf:"bytes,14,opt,name=Imsi,proto3" json:"Imsi,omitempty"`
	Imei        string `protobuf:"bytes,15,opt,name=Imei,proto3" json:"Imei,omitempty"`
	Mac         string `protobuf:"bytes,16,opt,name=Mac,proto3" json:"Mac,omitempty"`
	Phone       string `protobuf:"bytes,17,opt,name=Phone,proto3" json:"Phone,omitempty"`
	OS          string `protobuf:"bytes,18,opt,name=OS,proto3" json:"OS,omitempty"`
	NetMode     string `protobuf:"bytes,19,opt,name=NetMode,proto3" json:"NetMode,omitempty"`
	Version     string `protobuf:"bytes,20,opt,name=Version,proto3" json:"Version,omitempty"`
	PhoneBrand  string `protobuf:"bytes,21,opt,name=PhoneBrand,proto3" json:"PhoneBrand,omitempty"`
	IDFA        string `protobuf:"bytes,24,opt,name=IDFA,proto3" json:"IDFA,omitempty"` // IOS设备标识
	SubId       int32  `protobuf:"varint,25,opt,name=SubId,proto3" json:"SubId,omitempty"`
	IP          string `protobuf:"bytes,26,opt,name=IP,proto3" json:"IP,omitempty"`
	PlateIcon   string `protobuf:"bytes,30,opt,name=PlateIcon,proto3" json:"PlateIcon,omitempty"`
}

func (x *AccountInfo) Reset() {
	*x = AccountInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_pb_login_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AccountInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountInfo) ProtoMessage() {}

func (x *AccountInfo) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_login_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountInfo.ProtoReflect.Descriptor instead.
func (*AccountInfo) Descriptor() ([]byte, []int) {
	return file_internal_pb_login_proto_rawDescGZIP(), []int{0}
}

func (x *AccountInfo) GetUId() int32 {
	if x != nil {
		return x.UId
	}
	return 0
}

func (x *AccountInfo) GetPlate() string {
	if x != nil {
		return x.Plate
	}
	return ""
}

func (x *AccountInfo) GetOpenId() string {
	if x != nil {
		return x.OpenId
	}
	return ""
}

func (x *AccountInfo) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *AccountInfo) GetNewPassword() string {
	if x != nil {
		return x.NewPassword
	}
	return ""
}

func (x *AccountInfo) GetChanId() string {
	if x != nil {
		return x.ChanId
	}
	return ""
}

func (x *AccountInfo) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *AccountInfo) GetSex() int32 {
	if x != nil {
		return x.Sex
	}
	return 0
}

func (x *AccountInfo) GetIcon() string {
	if x != nil {
		return x.Icon
	}
	return ""
}

func (x *AccountInfo) GetImsi() string {
	if x != nil {
		return x.Imsi
	}
	return ""
}

func (x *AccountInfo) GetImei() string {
	if x != nil {
		return x.Imei
	}
	return ""
}

func (x *AccountInfo) GetMac() string {
	if x != nil {
		return x.Mac
	}
	return ""
}

func (x *AccountInfo) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *AccountInfo) GetOS() string {
	if x != nil {
		return x.OS
	}
	return ""
}

func (x *AccountInfo) GetNetMode() string {
	if x != nil {
		return x.NetMode
	}
	return ""
}

func (x *AccountInfo) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *AccountInfo) GetPhoneBrand() string {
	if x != nil {
		return x.PhoneBrand
	}
	return ""
}

func (x *AccountInfo) GetIDFA() string {
	if x != nil {
		return x.IDFA
	}
	return ""
}

func (x *AccountInfo) GetSubId() int32 {
	if x != nil {
		return x.SubId
	}
	return 0
}

func (x *AccountInfo) GetIP() string {
	if x != nil {
		return x.IP
	}
	return ""
}

func (x *AccountInfo) GetPlateIcon() string {
	if x != nil {
		return x.PlateIcon
	}
	return ""
}

type CreateAccountReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AccountInfo *AccountInfo `protobuf:"bytes,1,opt,name=AccountInfo,proto3" json:"AccountInfo,omitempty"`
}

func (x *CreateAccountReq) Reset() {
	*x = CreateAccountReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_pb_login_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateAccountReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAccountReq) ProtoMessage() {}

func (x *CreateAccountReq) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_login_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAccountReq.ProtoReflect.Descriptor instead.
func (*CreateAccountReq) Descriptor() ([]byte, []int) {
	return file_internal_pb_login_proto_rawDescGZIP(), []int{1}
}

func (x *CreateAccountReq) GetAccountInfo() *AccountInfo {
	if x != nil {
		return x.AccountInfo
	}
	return nil
}

type CreateAccountResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UId    int32  `protobuf:"varint,1,opt,name=UId,proto3" json:"UId,omitempty"`
	NewId  int32  `protobuf:"varint,2,opt,name=NewId,proto3" json:"NewId,omitempty"`
	ChanId string `protobuf:"bytes,3,opt,name=ChanId,proto3" json:"ChanId,omitempty"`
}

func (x *CreateAccountResp) Reset() {
	*x = CreateAccountResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_pb_login_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateAccountResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAccountResp) ProtoMessage() {}

func (x *CreateAccountResp) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_login_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAccountResp.ProtoReflect.Descriptor instead.
func (*CreateAccountResp) Descriptor() ([]byte, []int) {
	return file_internal_pb_login_proto_rawDescGZIP(), []int{2}
}

func (x *CreateAccountResp) GetUId() int32 {
	if x != nil {
		return x.UId
	}
	return 0
}

func (x *CreateAccountResp) GetNewId() int32 {
	if x != nil {
		return x.NewId
	}
	return 0
}

func (x *CreateAccountResp) GetChanId() string {
	if x != nil {
		return x.ChanId
	}
	return ""
}

type LoginParams struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DistinctId string  `protobuf:"bytes,1,opt,name=DistinctId,proto3" json:"DistinctId,omitempty"`
	TimeZone   float64 `protobuf:"fixed64,2,opt,name=TimeZone,proto3" json:"TimeZone,omitempty"`
}

func (x *LoginParams) Reset() {
	*x = LoginParams{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_pb_login_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LoginParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginParams) ProtoMessage() {}

func (x *LoginParams) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_login_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginParams.ProtoReflect.Descriptor instead.
func (*LoginParams) Descriptor() ([]byte, []int) {
	return file_internal_pb_login_proto_rawDescGZIP(), []int{3}
}

func (x *LoginParams) GetDistinctId() string {
	if x != nil {
		return x.DistinctId
	}
	return ""
}

func (x *LoginParams) GetTimeZone() float64 {
	if x != nil {
		return x.TimeZone
	}
	return 0
}

type LoginParamsReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UId    int32        `protobuf:"varint,1,opt,name=UId,proto3" json:"UId,omitempty"`
	Params *LoginParams `protobuf:"bytes,2,opt,name=Params,proto3" json:"Params,omitempty"`
}

func (x *LoginParamsReq) Reset() {
	*x = LoginParamsReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_pb_login_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LoginParamsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginParamsReq) ProtoMessage() {}

func (x *LoginParamsReq) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_login_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginParamsReq.ProtoReflect.Descriptor instead.
func (*LoginParamsReq) Descriptor() ([]byte, []int) {
	return file_internal_pb_login_proto_rawDescGZIP(), []int{4}
}

func (x *LoginParamsReq) GetUId() int32 {
	if x != nil {
		return x.UId
	}
	return 0
}

func (x *LoginParamsReq) GetParams() *LoginParams {
	if x != nil {
		return x.Params
	}
	return nil
}

type BindAccountReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ReserveOpenId string `protobuf:"bytes,1,opt,name=ReserveOpenId,proto3" json:"ReserveOpenId,omitempty"`
	AddPlate      string `protobuf:"bytes,2,opt,name=AddPlate,proto3" json:"AddPlate,omitempty"`
	AddOpenId     string `protobuf:"bytes,3,opt,name=AddOpenId,proto3" json:"AddOpenId,omitempty"`
	IsReward      bool   `protobuf:"varint,4,opt,name=IsReward,proto3" json:"IsReward,omitempty"`
}

func (x *BindAccountReq) Reset() {
	*x = BindAccountReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_pb_login_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BindAccountReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BindAccountReq) ProtoMessage() {}

func (x *BindAccountReq) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_login_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BindAccountReq.ProtoReflect.Descriptor instead.
func (*BindAccountReq) Descriptor() ([]byte, []int) {
	return file_internal_pb_login_proto_rawDescGZIP(), []int{5}
}

func (x *BindAccountReq) GetReserveOpenId() string {
	if x != nil {
		return x.ReserveOpenId
	}
	return ""
}

func (x *BindAccountReq) GetAddPlate() string {
	if x != nil {
		return x.AddPlate
	}
	return ""
}

func (x *BindAccountReq) GetAddOpenId() string {
	if x != nil {
		return x.AddOpenId
	}
	return ""
}

func (x *BindAccountReq) GetIsReward() bool {
	if x != nil {
		return x.IsReward
	}
	return false
}

var File_internal_pb_login_proto protoreflect.FileDescriptor

var file_internal_pb_login_proto_rawDesc = []byte{
	0x0a, 0x17, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x70, 0x62, 0x2f, 0x6c, 0x6f,
	0x67, 0x69, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70, 0x62, 0x22, 0xed, 0x03,
	0x0a, 0x0b, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x10, 0x0a,
	0x03, 0x55, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x55, 0x49, 0x64, 0x12,
	0x14, 0x0a, 0x05, 0x50, 0x6c, 0x61, 0x74, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x50, 0x6c, 0x61, 0x74, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x4f, 0x70, 0x65, 0x6e, 0x49, 0x64, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x4f, 0x70, 0x65, 0x6e, 0x49, 0x64, 0x12, 0x16, 0x0a,
	0x06, 0x4d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x4d,
	0x65, 0x74, 0x68, 0x6f, 0x64, 0x12, 0x20, 0x0a, 0x0b, 0x4e, 0x65, 0x77, 0x50, 0x61, 0x73, 0x73,
	0x77, 0x6f, 0x72, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x4e, 0x65, 0x77, 0x50,
	0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x43, 0x68, 0x61, 0x6e, 0x49,
	0x64, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x43, 0x68, 0x61, 0x6e, 0x49, 0x64, 0x12,
	0x1a, 0x0a, 0x08, 0x4e, 0x69, 0x63, 0x6b, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x0a, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x4e, 0x69, 0x63, 0x6b, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x53,
	0x65, 0x78, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x53, 0x65, 0x78, 0x12, 0x12, 0x0a,
	0x04, 0x49, 0x63, 0x6f, 0x6e, 0x18, 0x0d, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x49, 0x63, 0x6f,
	0x6e, 0x12, 0x12, 0x0a, 0x04, 0x49, 0x6d, 0x73, 0x69, 0x18, 0x0e, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x49, 0x6d, 0x73, 0x69, 0x12, 0x12, 0x0a, 0x04, 0x49, 0x6d, 0x65, 0x69, 0x18, 0x0f, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x49, 0x6d, 0x65, 0x69, 0x12, 0x10, 0x0a, 0x03, 0x4d, 0x61, 0x63,
	0x18, 0x10, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x4d, 0x61, 0x63, 0x12, 0x14, 0x0a, 0x05, 0x50,
	0x68, 0x6f, 0x6e, 0x65, 0x18, 0x11, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x50, 0x68, 0x6f, 0x6e,
	0x65, 0x12, 0x0e, 0x0a, 0x02, 0x4f, 0x53, 0x18, 0x12, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x4f,
	0x53, 0x12, 0x18, 0x0a, 0x07, 0x4e, 0x65, 0x74, 0x4d, 0x6f, 0x64, 0x65, 0x18, 0x13, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x4e, 0x65, 0x74, 0x4d, 0x6f, 0x64, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x56,
	0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x14, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x56, 0x65,
	0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x1e, 0x0a, 0x0a, 0x50, 0x68, 0x6f, 0x6e, 0x65, 0x42, 0x72,
	0x61, 0x6e, 0x64, 0x18, 0x15, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x50, 0x68, 0x6f, 0x6e, 0x65,
	0x42, 0x72, 0x61, 0x6e, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x49, 0x44, 0x46, 0x41, 0x18, 0x18, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x49, 0x44, 0x46, 0x41, 0x12, 0x14, 0x0a, 0x05, 0x53, 0x75, 0x62,
	0x49, 0x64, 0x18, 0x19, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x53, 0x75, 0x62, 0x49, 0x64, 0x12,
	0x0e, 0x0a, 0x02, 0x49, 0x50, 0x18, 0x1a, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x49, 0x50, 0x12,
	0x1c, 0x0a, 0x09, 0x50, 0x6c, 0x61, 0x74, 0x65, 0x49, 0x63, 0x6f, 0x6e, 0x18, 0x1e, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x09, 0x50, 0x6c, 0x61, 0x74, 0x65, 0x49, 0x63, 0x6f, 0x6e, 0x22, 0x45, 0x0a,
	0x10, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x65,
	0x71, 0x12, 0x31, 0x0a, 0x0b, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x49, 0x6e, 0x66, 0x6f,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x70, 0x62, 0x2e, 0x41, 0x63, 0x63, 0x6f,
	0x75, 0x6e, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x0b, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74,
	0x49, 0x6e, 0x66, 0x6f, 0x22, 0x53, 0x0a, 0x11, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x41, 0x63,
	0x63, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x12, 0x10, 0x0a, 0x03, 0x55, 0x49, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x55, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x4e,
	0x65, 0x77, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x4e, 0x65, 0x77, 0x49,
	0x64, 0x12, 0x16, 0x0a, 0x06, 0x43, 0x68, 0x61, 0x6e, 0x49, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x43, 0x68, 0x61, 0x6e, 0x49, 0x64, 0x22, 0x49, 0x0a, 0x0b, 0x4c, 0x6f, 0x67,
	0x69, 0x6e, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x12, 0x1e, 0x0a, 0x0a, 0x44, 0x69, 0x73, 0x74,
	0x69, 0x6e, 0x63, 0x74, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x44, 0x69,
	0x73, 0x74, 0x69, 0x6e, 0x63, 0x74, 0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x54, 0x69, 0x6d, 0x65,
	0x5a, 0x6f, 0x6e, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x01, 0x52, 0x08, 0x54, 0x69, 0x6d, 0x65,
	0x5a, 0x6f, 0x6e, 0x65, 0x22, 0x4b, 0x0a, 0x0e, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x50, 0x61, 0x72,
	0x61, 0x6d, 0x73, 0x52, 0x65, 0x71, 0x12, 0x10, 0x0a, 0x03, 0x55, 0x49, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x03, 0x55, 0x49, 0x64, 0x12, 0x27, 0x0a, 0x06, 0x50, 0x61, 0x72, 0x61,
	0x6d, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x70, 0x62, 0x2e, 0x4c, 0x6f,
	0x67, 0x69, 0x6e, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x52, 0x06, 0x50, 0x61, 0x72, 0x61, 0x6d,
	0x73, 0x22, 0x8c, 0x01, 0x0a, 0x0e, 0x42, 0x69, 0x6e, 0x64, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e,
	0x74, 0x52, 0x65, 0x71, 0x12, 0x24, 0x0a, 0x0d, 0x52, 0x65, 0x73, 0x65, 0x72, 0x76, 0x65, 0x4f,
	0x70, 0x65, 0x6e, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x52, 0x65, 0x73,
	0x65, 0x72, 0x76, 0x65, 0x4f, 0x70, 0x65, 0x6e, 0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x41, 0x64,
	0x64, 0x50, 0x6c, 0x61, 0x74, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x41, 0x64,
	0x64, 0x50, 0x6c, 0x61, 0x74, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x41, 0x64, 0x64, 0x4f, 0x70, 0x65,
	0x6e, 0x49, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x41, 0x64, 0x64, 0x4f, 0x70,
	0x65, 0x6e, 0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x49, 0x73, 0x52, 0x65, 0x77, 0x61, 0x72, 0x64,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x49, 0x73, 0x52, 0x65, 0x77, 0x61, 0x72, 0x64,
	0x42, 0x06, 0x5a, 0x04, 0x2e, 0x3b, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_internal_pb_login_proto_rawDescOnce sync.Once
	file_internal_pb_login_proto_rawDescData = file_internal_pb_login_proto_rawDesc
)

func file_internal_pb_login_proto_rawDescGZIP() []byte {
	file_internal_pb_login_proto_rawDescOnce.Do(func() {
		file_internal_pb_login_proto_rawDescData = protoimpl.X.CompressGZIP(file_internal_pb_login_proto_rawDescData)
	})
	return file_internal_pb_login_proto_rawDescData
}

var file_internal_pb_login_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_internal_pb_login_proto_goTypes = []interface{}{
	(*AccountInfo)(nil),       // 0: pb.AccountInfo
	(*CreateAccountReq)(nil),  // 1: pb.CreateAccountReq
	(*CreateAccountResp)(nil), // 2: pb.CreateAccountResp
	(*LoginParams)(nil),       // 3: pb.LoginParams
	(*LoginParamsReq)(nil),    // 4: pb.LoginParamsReq
	(*BindAccountReq)(nil),    // 5: pb.BindAccountReq
}
var file_internal_pb_login_proto_depIdxs = []int32{
	0, // 0: pb.CreateAccountReq.AccountInfo:type_name -> pb.AccountInfo
	3, // 1: pb.LoginParamsReq.Params:type_name -> pb.LoginParams
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_internal_pb_login_proto_init() }
func file_internal_pb_login_proto_init() {
	if File_internal_pb_login_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_internal_pb_login_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AccountInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_pb_login_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateAccountReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_pb_login_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateAccountResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_pb_login_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LoginParams); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_pb_login_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LoginParamsReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_pb_login_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BindAccountReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_internal_pb_login_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_pb_login_proto_goTypes,
		DependencyIndexes: file_internal_pb_login_proto_depIdxs,
		MessageInfos:      file_internal_pb_login_proto_msgTypes,
	}.Build()
	File_internal_pb_login_proto = out.File
	file_internal_pb_login_proto_rawDesc = nil
	file_internal_pb_login_proto_goTypes = nil
	file_internal_pb_login_proto_depIdxs = nil
}
